### ISSUE TITLE
 AdoptOpenJDK does not work in window7 sp1

### ISSUE THREAD

**Issue by linspinho** [AdoptOpenJDK/openjdk-build#1098]
None of my java application works after AdoptOpenJDK install. 
java -verision works and show AdoptOpenJDK version.

netbeans does not works, it show  
'invalid jdkhome specified'
 Cannot locate java installation in specified jdkhome:
 C:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-openj9\bin
 Do you want to try to use default version?
 
on click yes 

shows another error

Cannot find Java 1.8 or higher

window path:C:\Program Files\AdoptOpenJDK\jre-11.0.3.7-openj9\bin;C:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-openj9\bin;

`C:\Users\owner>java -jar "C:\Users\MJRN\Documents\apps\geobti-1.1.0.beta-RELEASE.jar"

 
 :: Spring Boot ::        (v1.5.9.RELEASE)

2019-05-22 18:17:16.392  INFO 5564 --- [           main] com.obti.GeobtiApplication               : 

Caused by: java.lang.NoClassDefFoundError: javax.xml.bind.ValidationEventHandler
        at org.hibernate.boot.spi.XmlMappingBinderAccess.<init>(XmlMappingBinderAccess.java:43) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
        at org.hibernate.boot.MetadataSources.<init>(MetadataSources.java:87) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:179) ~[hibernate-entitymanager-5.0.12.Final.jar!/:5.0.12.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:149) ~[hibernate-entitymanager-5.0.12.Final.jar!/:5.0.12.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:54) ~[spring-orm-

4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:360) ~[spring-orm-

4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:382) ~[spring-orm-

4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:371) ~[spring-orm-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:336) ~[spring-orm-

4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-

4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-

4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        ... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationEventHandler
        at java.base/java.net.URLClassLoader.findClass(Unknown Source) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClassHelper(Unknown Source) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[geobti-1.1.0.beta-RELEASE.jar:1.1.0.beta-RELEASE]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
        ... 35 common frames omitted
`

**Comment by pshipton** [comment]
Does it work with the Hotspot version?

**Comment by pshipton** [comment]
javax.xml.bind.ValidationEventHandler is only available in JDK8, maybe you need to use the JDK8 version.

See http://openjdk.java.net/jeps/320, the javax.xml.bind is removed in Java 11.

**Comment by linspinho** [comment]
> Does it work with the Hotspot version?

I did not try AdoptOpenJDK hotspot.


> javax.xml.bind.ValidationEventHandler is only available in JDK8, maybe you need to use the JDK8 version.
> 
> See http://openjdk.java.net/jeps/320, the javax.xml.bind is removed in Java 11.

I just confirmed that!

Netbeans 8.2 did not work with this openJDK, maybe because it was working with Oracle JDK 8 before.

I have installed Apache Netbeans 11 and it seems work just fine.

Thanks for your time and hard work.
