### ISSUE TITLE
Installer issues with OpenJDK 8 on Debian 10 Stretch

### ISSUE THREAD

**Issue by energy-cloud** [AdoptOpenJDK/openjdk-build#1203]
Please raise an issue at https://github.com/AdoptOpenJDK/openjdk-installer or https://github.com/AdoptOpenJDK/homebrew-openjdk if it's an issue with our brew casks

Following install instructions here: https://adoptopenjdk.net/installation.html#linux-pkg
but it's failing on install.

OS
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

Issues happen even when running the following first:
sudo apt-get install -y software-properties-common
________________________________
sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/

Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster
_____________________________________

**Comment by aahlenst** [comment]
We don't publish separate packages for Raspbian. You can use the Debian packages, though:

```
echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster main" | sudo tee /etc/apt/sources.list.d/adoptopenjdk.list
```

Please note that there are only releases for `arm64`, not `armhf`. `armhf` should become available in a few days.
