### ISSUE TITLE
The JPad application doesn't start with OpenJDK

### ISSUE THREAD

**Issue by Auto72** [AdoptOpenJDK/openjdk-build#1240]
**Platform:**
Windows 10, 7

**Architecture:**
x86, x64

The JPad application (http://jpad.io/) doesn't start with OpenJDK.

**Comment by karianna** [comment]
@Auto72 We'll need more information - what version of AdoptOpenJDK are you using and what error message are you getting?

**Comment by Auto72** [comment]
About version of AdoptOpenJDK:

C:\>java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

About Error Details:

OS=Windows 10
Java=1.8.0_222
Des=unknown
Stack=java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1353)
	at io.jpad.JPadLauncher.main(JPadLauncher.java:81)
Caused by: java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at io.jpad.JPadFrame.<init>(JPadFrame.java:177)
	at io.jpad.JPadLauncher.launch(JPadLauncher.java:110)
	at io.jpad.JPadLauncher.access$200(JPadLauncher.java:31)
	at io.jpad.JPadLauncher$2.run(JPadLauncher.java:83)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

You can download the JPad application (http://jpad.io/) yourself and double check.
Thanks.

**Comment by karianna** [comment]
Ah, this is because OpenJDK does not come bundled with OpenJFX and we don't bundle it automatically at AdotpOpenJDK either.

See #577
