### ISSUE TITLE
issue while starting OC with Adapt

### ISSUE THREAD

**Issue by NetOps-spectrum** [AdoptOpenJDK/openjdk-build#1447]
Selecting proxy for: http://<<Servername>>:<<Port>>/$Product/<<AppName>>.jnlp
Selecting proxy for: http://<<Servername>>:<<Port>>/$Product/<<AppName>>.jnlp
Selected proxies: [DIRECT]

netx: Read Error: Could not read or parse the JNLP file. (java.lang.NullPointerException: name can't be null (name can't be null))

net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.

        at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)

        at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)

        at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)

        at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)

        at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)

        at java.security.AccessController.doPrivileged(Native Method)

        at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)

Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null

        at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)

        at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:240)

        at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)

        at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)

        at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)

        at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)

        ... 6 more

Caused by: java.lang.NullPointerException: name can't be null

        at java.io.FilePermission.init(FilePermission.java:205)

        at java.io.FilePermission.<init>(FilePermission.java:305)

        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)

        at java.io.FileInputStream.<init>(FileInputStream.java:127)

        at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)

        ... 11 more

 

Downloading http://<<Servername>>:<<Port>>/$Product/<<AppName>>.jnlp using http://<<Servername>>:<<Port>>/$Product/<<AppName>>.jnlp (encoding : null)

java.lang.StringIndexOutOfBoundsException: String index out of range: -1

        at java.lang.String.substring(String.java:1927)

        at net.sourceforge.jnlp.cache.CacheUtil.pathToURLPath(CacheUtil.java:555)

        at net.sourceforge.jnlp.cache.CacheUtil.getCacheFileIfExist(CacheUtil.java:539)

        at net.sourceforge.jnlp.cache.CacheUtil.getCacheFile(CacheUtil.java:511)

        at net.sourceforge.jnlp.cache.CacheEntry.<init>(CacheEntry.java:61)

        at net.sourceforge.jnlp.cache.ResourceDownloader.downloadFile(ResourceDownloader.java:412)

        at net.sourceforge.jnlp.cache.ResourceDownloader.downloadResource(ResourceDownloader.java:364)

        at net.sourceforge.jnlp.cache.ResourceDownloader.run(ResourceDownloader.java:118)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)

 

Disconnecting sun.net.www.protocol.http.HttpURLConnection:http://<<Servername>>:<<Port>>/$Product/<<AppName>>.jnlp

**Comment by NetOps-spectrum** [comment]
Any update?
