### ISSUE TITLE
openjdk-build-pr-tester can't handle JDK14/15 properly

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#1593]
Well it might be able to handle 15/HEAD properly but it definately can't handle 14 as it comes back with this. We need this working to be able to validate stuff on the current release lines

```
[Pipeline] End of Pipeline
java.nio.file.NoSuchFileException: /home/jenkins/.jenkins/workspace/build-scripts-pr-tester/test-build-script-pull-request/pipelines/jobs/configurations/jdk14u.groovy
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
```

**Comment by karianna** [comment]
Fixed via #1603 1603
