### ISSUE TITLE
AIX Open9 JDK8 and 11 builds failing

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1733]
I've been lookjing at this for a few days and want to make sure I'm recording everything properly.

Current situation:
- JDK8 [fails on our AIX 7100-05-05-1939 build machines](https://github.com/eclipse/openj9/issues/9369) because the `ddrgen` utility does not run without crashing. This appears to have become a hard requirement around the 22nd April with the JDK8 and JDK11 code, but not JDK14
- The crash is likely as a result of the tools supplied in an older AIX level (7100-04-01-1543 vs 7100-05-05-1939) (See also https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1006 which was a request, then canceled, to switch OpenJ9 to 7.15SP5)
- Running the `ddrgen` phase within a build on a 7.15SP5 system [test-ibm-ppc64-aix-71-1](https://ci.adoptopenjdk.net/computer/test-ibm-ppc64-aix-71-1) (with later `dump` command) works for building JDK8/J9 with an adoptyopenjdk8 boot JDK
- JDK7 which was used on the old build machines used for bootstrapping JDK8 appears to be an openjdk of unclear origin (possibly compiled by this project in the past) and is not referenced in the playbooks
- Copying the openjdk7 from the existing build machine onto the new one worked for [HotSpot](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/557/) but not [OpenJ9](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/653/) on first run
- The IBM Java 7 that was on the 7.1SP5 machine does not appear to work as a boot JDK for openjdk8
- AdoptOpenJDK8 does work as a boot JDK for openjdk8 builds, but that is less desirable than using JDK7 which we use elsewhere
- Building java 11 on the 7.1SP5 machine (`5.0.0(2)` vs `4.3.30(1)` on the old system) failes due to an issue with bash and pipe limits `cannot make pipe for process substitution: No such file or directory` (https://github.com/eclipse/openj9/issues/9369#issuecomment-624634760)
- Copying the `bash` binary from the existing build machine to the new one stops the JDK11 process crash

**Comment by sxa** [comment]
Tried reducing the JDK11 build to just use 3 cores but the bash error still persists - I'm going to leave it with the old bash version copired from the other machine for now to mitigate this:
```
/usr/bin/bash: /tmp//sh-np.FfrMac: ambiguous redirect
gmake[3]: *** [Awt2dLibraries.gmk:603: /home/sxa/openjdk-build/workspace/build/src/build/aix-ppc64-normal-server-release/support/native/java.desktop/libfontmanager/hb-map.o] Error 1
gmake[3]: *** Waiting for unfinished jobs....
```

**Comment by sxa** [comment]
JDK8 boot JDK options:
[/home/sxa/jdk8u252-b09](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/659/consoleFull) - Works ok
[/usr/java7_64](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/662/console) - Works ok
/usr/java7
[/home/jenkins/j2sdk-image](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/660/consoleFull) (JDK from old build machine)
```
Creating images/lib/ct.sym
Compiling tools to generate DDR pointer classes and structure stubs
Generating DDR pointer class source files
Generating DDR structure stub source files
Generating DDR pointer and structure class files
superset directory name : /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-openj9/workspace/build/src/build/aix-ppc64-normal-server-release/vm/
superset file name : superset.dat
superset directory name : /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-openj9/workspace/build/src/build/aix-ppc64-normal-server-release/vm/
superset file name : superset.dat
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/jenkins/j2sdk-image/jre/lib/ppc64/xawt/libmawt.so: /home/jenkins/j2sdk-image/jre/lib/ppc64/xawt/libmawt.so, LIBPATH=/home/jenkins/j2sdk-image/jre/lib/ppc64/server:/home/jenkins/j2sdk-image/jre/lib/ppc64:/home/jenkins/j2sdk-image/jre/lib/ppc64/jli:/home/jenkins/j2sdk-image/jre/../lib/ppc64:/opt/freeware/lib:/usr/java8_64/jre/lib/ppc64/j9vm:/usr/java8_64/jre/lib/ppc64:/usr/java8_64/jre/../lib/ppc64:/usr/java8_64/jre/lib/icc:/usr/lib, LD_LIBRARY_PATH= : 	0509-130 Symbol resolution failed for /home/jenkins/j2sdk-image/jre/lib/ppc64/xawt/libmawt.so because:
	0509-136   Symbol XRenderCreateRadialGradient (number 329) is not exported from
		   dependent module /opt/freeware/lib/libXrender.a[libXrender.so.0].
	0509-136   Symbol XRenderCreateLinearGradient (number 330) is not exported from
		   dependent module /opt/freeware/lib/libXrender.a[libXrender.so.0].
	0509-022 Cannot load module /home/jenkins/j2sdk-image/jre/lib/ppc64/xawt/libmawt.so.
	0509-026 System error: Cannot run a file that does not have a valid
```

**Comment by sxa** [comment]
Above output was with the default JDK in the PATH being a JDK7. When set to 8 the following occurs for the boot JDK:
[/home/jenkins/j2sdk-image](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/668/consoleFull): Works ok :-D

/usr/java7_64:
/home/sxa/jdk8u252-b09:

**Comment by sxa** [comment]
NOTE: Using a n IBM Java 8 in the PATH [does not appear to allow Gradle to run properly](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/678/console), therefore I am switching `/usr/bin/java` on the machine to point to an adoptopenjdk (Hotspot) build. This is the failure for future reference:
```
BUILD SUCCESSFUL in 40s
3 actionable tasks: 2 executed, 1 up-to-date
Exception in thread "main" java.lang.IllegalArgumentException: No group with name <pre>
	at java.util.regex.Matcher.getMatchedGroupIndex(Matcher.java:1327)
	at java.util.regex.Matcher.group(Matcher.java:583)
	at java_util_regex_Matcher$group$0.call(Unknown Source)
	at 
```

**Comment by sxa** [comment]
All now resolved
