### ISSUE TITLE
Windows test jobs fail: No such property: HOME for class: WorkflowScript

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1807]
**Platform:**
Windows
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_x86-64_windows_xl/182/console
```
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: HOME for class: WorkflowScript
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:355)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:354)
	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:353)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:357)
```

**Comment by M-Davies** [comment]
Dup of https://github.com/AdoptOpenJDK/openjdk-tests/issues/1803
