### ISSUE TITLE
Workspace has a corrupt .git repository, causing Test build failures 

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1908]
**Platform:**
Test_openjdk11_j9_sanity.openjdk_x86-64_windows
Test_openjdk11_hs_sanity.openjdk_x86-64_windows
Test_openjdk14_hs_sanity.openjdk_x86-64_windows
Test_openjdk8_j9_sanity.openjdk_x86-64_windows_xl
Test_openjdk8_hs_sanity.openjdk_x86-64_windows
Test_openjdk14_j9_sanity.openjdk_x86-64_windows

**Architecture:**

Please describe the issue that you are having with our binaries and if possible how to recreate it.
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_x86-64_windows/249/console

```
Obtained buildenv/jenkins/openjdk_tests from git https://github.com/AdoptOpenJDK/openjdk-tests.git
Running in Durability level: PERFORMANCE_OPTIMIZED
[Pipeline] Start of Pipeline
[Pipeline] echo
SPEC: win_x86-64_cmprssptrs
[Pipeline] echo
LABEL: ci.role.test&&hw.arch.x86&&sw.os.windows
[Pipeline] stage
[Pipeline] { (Queue)
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on ‘ci.role.test&&hw.arch.x86&&sw.os.windows’
Running on test-aws-win2019-x64-2 in C:\Users\jenkins.EC2AMAZ-T7I06S9\workspace\Test_openjdk11_hs_sanity.openjdk_x86-64_windows
[Pipeline] {
[Pipeline] checkout
No credentials specified
 > git rev-parse --is-inside-work-tree # timeout=10
ERROR: Workspace has a .git repository, but it appears to be corrupt.
hudson.plugins.git.GitException: Command "git rev-parse --is-inside-work-tree" returned status code 128:
stdout: 
stderr: fatal: not a git repository (or any parent up to mount point /cygdrive)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2360)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2356)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1916)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1928)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.hasGitRepo(CliGitAPIImpl.java:343)
	at hudson.plugins.git.GitAPI.hasGitRepo(GitAPI.java:232)
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:929)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:903)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:855)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:97)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by M-Davies** [comment]
@Willsparker Do you have access to clean this up?

**Comment by AdamBrousseau** [comment]
The test jobs clean workspace at the end so these would have had to fall over pretty hard on the previous run to not get cleaned up. Either that or there's a problem removing the contents. It appears to cleanup successfully after the run in the link. Can you try running the same test job on the same machine? Unless there's a problem with the cleanup, I expect this would have resolved itself.

**Comment by Willsparker** [comment]
FYI. All of these are on a single machine- `test-aws-win2019-x64-2` , which I've cleared now. I'll keep an eye on if it happens again on the same machine.

Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1396

**Comment by M-Davies** [comment]
Thanks @Willsparker
