### ISSUE TITLE
Connection refused / Connection Failure causing nightly builds fail

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1921]
**jdk11u-windows-x64-openj9-windowsXL**
**jdk8u-windows-x64-openj9**
**jdk8u-windows-x86-32-openj9**

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9-windowsXL/389/console

`00:32:13  Downloading https://services.gradle.org/distributions/gradle-6.5-bin.zip
00:32:35  
00:32:35  Exception in thread "main" java.net.ConnectException: Connection timed out: connect
00:32:35  	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
00:32:35  	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
00:32:35  	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
00:32:35  	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
00:32:35  	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
00:32:35  	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
00:32:35  	at java.base/java.net.Socket.connect(Socket.java:591)
00:32:35  	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
00:32:35  	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
00:32:35  	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
00:32:35  	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
00:32:35  	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
00:32:35  	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
00:32:35  	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
00:32:35  	at java `

**jdk8u-linux-ppc64le-openj9-linuxXL**
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9-linuxXL/221/console

`20:36:06  Starting building: build-scripts » release » create_installer_linux #12650
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
20:36:06  Execution error: org.jenkinsci.plugins.workflow.steps.FlowInterruptedException`

**jdk-linux-aarch64-openj9**
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-aarch64-openj9/34/console

` CompileJavaModules.gmk:594: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk/jdk-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/java.desktop/_the.java.desktop_batch' failed
05:30:01  gmake[3]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk/jdk-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/java.desktop/_the.java.desktop_batch] Error 1
05:30:01  make/Main.gmk:197: recipe for target 'java.desktop-java' failed
05:30:01  gmake[2]: *** [java.desktop-java] Error 1
05:30:01  
05:30:01  ERROR: Build failed for targets 'product-images legacy-jre-image test-image debug-image' in configuration 'linux-aarch64-server-release' (exit code 2) 
05:30:01  Stopping sjavac server`

**jdk14u-aix-ppc64-hotspot**
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-aix-ppc64-hotspot/110/console

`23:35:06      1500-029: (W) WARNING: subprogram JNIEnv_::NewObject(_jclass *, _jmethodID *, ...) could not be inlined into startAgentThreadWrapper(JNIEnv_ *, _jvmtiEnv *).
23:41:55  
23:41:55  ERROR: Build failed for targets 'product-images legacy-jre-image test-image' in configuration 'aix-ppc64-server-release' (exit code 2) 
23:41:55  
23:41:55  === Output from failing command(s) repeated here ===
23:41:55  * For target support_demos_classes_jfc_CodePointIM__the.BUILD_DEMO_CodePointIM_batch:
23:41:55  Connection attempt failed: Connection refused
23:41:55  Connection attempt failed: Connection refused
23:41:55  Connection attempt failed: Connection refused
23:41:55  Giving up
23:41:55  IOException caught during compilation: Could not connect to server
23:41:55  `

**Comment by karianna** [comment]
@Willsparker - Is this more of an infra thing?

**Comment by Willsparker** [comment]
@karianna While all the windows ones were on a single machine it seems to be okay now - @sxa set off a few rebuilds this morning and they passed:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-openj9/606/
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9/739/
The last one looks like it may be an intermittent issue with the machine, as it happened earlier in the evening (as documented at https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1407 )
Not so sure about the rest
