### ISSUE TITLE
dockerBuild fails if node host user UID is not 1000

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2005]
In trying to create a dockerBuild node, discovered having created a jenkins user with uid=1001 that dockerBuild fails with ```
10:33:18   > git checkout -f ac64818c12047d4da21c4f7e833f5deff1a4101c # timeout=10
10:33:19  sh: /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-x64-openj9@tmp/durable-0ab7d979/jenkins-log.txt: Permission denied
10:33:19  sh: /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-x64-openj9@tmp/durable-0ab7d979/jenkins-result.txt.tmp: Permission denied
10:33:19  mv: accessing `/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-x64-openj9@tmp/durable-0ab7d979/jenkins-result.txt': Permission denied
```
The reason being because the adoptopenjdk docker images have the jenkins user set to uid=1000, which happens to match the adoptopenjdk Azure cloud uid of 1000.
It would be good to match the image to the host environment, or make the built image handle this dynamically?

**Comment by sxa** [comment]
@gdams As per the [slack thread](https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1596121051329700), can you look at this please? Not sure where the logic is that determines how the mapping is defined for the `dockerBulid` host situation

**Comment by Willsparker** [comment]
I'm assuming this is using the docker files at https://hub.docker.com/_/adoptopenjdk , not `makejdk-any-platform.sh --docker` ? 
Currently `dockerfile-generator.sh` creates a dockerfile that requires the user's UID passed into it to build an image from it (https://github.com/AdoptOpenJDK/openjdk-build/blob/16a43ec831090cc76594317fb7d585a099e21186/docker/dockerfile-generator.sh#L286) . This gives the docker container user the same UID as the host user's UID

**Comment by gdams** [comment]
hmm, maybe we should remove the user creation from the dockerfile... that would probably avoid this issue....

**Comment by Willsparker** [comment]
So it is from the dockerfiles created with `dockerfile-generator.sh` (via `./makejdk-any-platform --docker` ) ..? @andrew-m-leonard

**Comment by gdams** [comment]
@Willsparker it's using this dockerfile: https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/Dockerfile.CentOS6

The fix should be to remove the following steps:

```dockerfile
ARG user=jenkins

-----

RUN groupadd -g 1000 ${user}
RUN useradd -c "Jenkins user" -d /home/${user} -u 1000 -g 1000 -m ${user}
```

We should also remove them from the centos7 dockerfile https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/Dockerfile.CentOS7

**Comment by gdams** [comment]
@andrew-m-leonard a fix has been landed, can you please try again?

**Comment by andrew-m-leonard** [comment]
Nightly builds failing: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9/725/

**Comment by Willsparker** [comment]
Update: https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1597132129438300

Removing the Jenkins user didn't work to fix the issue, so the above PR was reverted, and the docker image was updated to how it was before ( after some issues, leading to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1506 and https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1505 ).

**Comment by AdamBrousseau** [comment]
I hit the same problem (as titled) but presents with a different error. I don't make it to the Git step.
```
00:05:59.625  Successfully built fc4d639a1687
00:05:59.625  Successfully tagged build-image:latest
[Pipeline] isUnix
[Pipeline] sh
00:06:01.755  + docker inspect -f . build-image
00:06:01.755  .
[Pipeline] withDockerContainer
00:06:04.049  ub16x64rt1 does not seem to be running inside a container
00:06:05.984  $ docker run -t -d -u 1001:1001 -w /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9 -v /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9:/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9:rw,z -v /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9@tmp:/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9@tmp:rw,z -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** build-image cat
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
00:06:08.309  Execution error: java.io.IOException: Failed to run image 'build-image'. Error: docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "chdir to cwd (\"/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9\") set in config.json failed: permission denied": unknown.
[Pipeline] echo
00:06:08.310  java.io.IOException: Failed to run image 'build-image'. Error: docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "chdir to cwd (\"/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9\") set in config.json failed: permission denied": unknown.
00:06:08.310  	at org.jenkinsci.plugins.docker.workflow.client.DockerClient.run(DockerClient.java:138)
00:06:08.310  	at org.jenkinsci.plugins.docker.workflow.WithContainerStep$Execution.start(WithContainerStep.java:198)
00:06:08.310  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
00:06:08.310  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
00:06:08.310  	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
00:06:08.310  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
00:06:08.310  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
00:06:08.310  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
00:06:08.310  	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
00:06:08.310  	at org.jenkinsci.plugins.docker.workflow.Docker$Image.inside(Docker.groovy:126)
00:06:08.310  	at org.jenkinsci.plugins.docker.workflow.Docker.node(Docker.groovy:66)
00:06:08.310  	at org.jenkinsci.plugins.docker.workflow.Docker$Image.inside(Docker.groovy:114)
00:06:08.310  	at org.jenkinsci.plugins.docker.workflow.Docker$Image.inside(Docker.groovy)
00:06:08.310  	at Build.build(Script2.groovy:701)
00:06:08.310  	at ___cps.transform___(Native Method)
00:06:08.310  	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
00:06:08.310  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
00:06:08.310  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
00:06:08.310  	at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
00:06:08.310  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:06:08.310  	at java.lang.reflect.Method.invoke(Method.java:498)
00:06:08.310  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
00:06:08.310  	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
00:06:08.310  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
00:06:08.310  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
00:06:08.310  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
00:06:08.310  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
00:06:08.310  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
00:06:08.310  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
00:06:08.310  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
00:06:08.310  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
00:06:08.310  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
00:06:08.310  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
00:06:08.310  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
00:06:08.310  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
00:06:08.310  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
00:06:08.310  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
00:06:08.310  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:06:08.310  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
00:06:08.310  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
00:06:08.310  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
00:06:08.310  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
00:06:08.310  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:06:08.310  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:06:08.310  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:06:08.310  	at java.lang.Thread.run(Thread.java:748)
00:06:08.310  
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
Finished: FAILURE
```
https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1600808233018800

Running on a host with a user jenkins/1000 is a workaround to the issue for me. Not preferable as I have far fewer machines with uid 1000 than I do 1001.
