### ISSUE TITLE
jdk11 Hotspot build fails: No group with name <pre>

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2209]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/789/console
```
00:11:04  openjdk version "11.0.9.1" 2020-11-04
00:11:04  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1-202011042348)
00:11:04  OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1-202011042348, mixed mode)
00:11:04  
[Pipeline] echo
00:11:04  matched
[Pipeline] echo
00:11:04  11.0.9.1+1-202011042348
[Pipeline] echo
00:11:04  [INFO] ATTEMPTING TO PARSE PUBLISH_NAME: 11.0.9.1+1-202011042348
[Pipeline] echo
00:11:04  [INFO] Attempting to match pre223 regex: jdk\-?(?<version>(?<major>[0-8]+)(u(?<update>[0-9]+))?(-b(?<build>[0-9]+))(_(?<opt>[-a-zA-Z0-9\.]+))?)
[Pipeline] echo
00:11:04  [WARNING] Failed to match pre223 regex.
[Pipeline] echo
00:11:05  [INFO] Attempting to match AltPre223 regex: (?<version>1\.(?<major>[0-8])\.0(_(?<update>[0-9]+))?(-(?<additional>.*))?)
[Pipeline] echo
00:11:05  [WARNING] Failed to match matchAltPre223 regex.
[Pipeline] echo
00:11:05  [INFO] Attempting to match223 regex: (?:jdk\-)?(?<version>(?<major>[0-9]+)(\.(?<minor>[0-9]+))?(\.(?<security>[0-9]+))?(\-(?<pre>[a-zA-Z0-9]+))?\+(?<build>[0-9]+)(\-(?<opt>[-a-zA-Z0-9\.]+))?)
[Pipeline] echo
00:11:05  [WARNING] Failed to match last 223 regex.
[Pipeline] echo
00:11:05  [INFO] Attempting to match223 regex: (?:jdk\-)?(?<version>(?<major>[0-9]+)(\.(?<minor>[0-9]+))?(\.(?<security>[0-9]+))?\-(?<pre>[a-zA-Z0-9]+)(\-(?<opt>[-a-zA-Z0-9\.]+))?)
[Pipeline] echo
00:11:05  [WARNING] Failed to match last 223 regex.
[Pipeline] echo
00:11:05  [INFO] Attempting to match223 regex: (?:jdk\-)?(?<version>(?<major>[0-9]+)(\.(?<minor>[0-9]+))?(\.(?<security>[0-9]+))?(\+\-(?<opt>[-a-zA-Z0-9\.]+))?)
[Pipeline] echo
00:11:05  [SUCCESS] match223 regex matched!
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
00:11:05  $ docker stop --time=1 9a242428d196d79c8262f2a705c3bf6992051dbe402f2b9868e35eb90222ad49
00:11:11  $ docker rm -f 9a242428d196d79c8262f2a705c3bf6992051dbe402f2b9868e35eb90222ad49
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
00:11:12  Execution error: java.lang.IllegalArgumentException: No group with name <pre>
[Pipeline] echo
00:11:12  java.lang.IllegalArgumentException: No group with name <pre>
00:11:12  	at java.util.regex.Matcher.getMatchedGroupIndex(Matcher.java:1316)
00:11:12  	at java.util.regex.Matcher.group(Matcher.java:572)
00:11:12  	at sun.reflect.GeneratedMethodAccessor36250.invoke(Unknown Source)
00:11:12  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:11:12  	at java.lang.reflect.Method.invoke(Method.java:498)
00:11:12  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
00:11:12  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
00:11:12  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
00:11:12  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
00:11:12  	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
00:11:12  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
00:11:12  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
00:11:12  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
00:11:12  	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
00:11:12  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
00:11:12  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
00:11:12  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
00:11:12  	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
00:11:12  	at common.VersionInfo.match223(VersionInfo.groovy:174)
00:11:12  	at common.VersionInfo.parse(VersionInfo.groovy:27)
00:11:12  	at Build.parseVersionOutput(Script2.groovy:257)
00:11:12  	at Build.buildScripts(Script2.groovy:834)
```

**Comment by adamfarley** [comment]
@andrew-m-leonard - Any connection to this?

NOTE: Using a n IBM Java 8 in the PATH [does not appear to allow Gradle to run properly](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/678/console), therefore I am switching `/usr/bin/java` on the machine to point to an adoptopenjdk (Hotspot) build. This is the failure for future reference:
```
BUILD SUCCESSFUL in 40s
3 actionable tasks: 2 executed, 1 up-to-date
Exception in thread "main" java.lang.IllegalArgumentException: No group with name <pre>
	at java.util.regex.Matcher.getMatchedGroupIndex(Matcher.java:1327)
	at java.util.regex.Matcher.group(Matcher.java:583)
	at java_util_regex_Matcher$group$0.call(Unknown Source)
	at 
```

_Originally posted by @sxa in https://github.com/AdoptOpenJDK/openjdk-build/issues/1733#issuecomment-628145392_

**Comment by andrew-m-leonard** [comment]
@adamfarley so possibly yes, i'm fixing the regex matcher as it was trying to query "groups" that were not in the regex which is illegal as per exception...
