### ISSUE TITLE
?!! Linux dockerBuild: The agent has not been fully initialized yet

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2244]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-linux-ppc64le-openj9/107/console
```
21:34:10  ERROR: Issue with creating launcher for agent osuosl-ppc64le-15208. The agent has not been fully initialized yet
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
21:34:11  Execution error: java.io.IOException: Failed to extract /home/ubuntu/workspace/build-scripts/jobs/jdk15u/jdk15u-linux-ppc64le-openj9/transfer of 8 files
[Pipeline] echo
21:34:11  java.io.IOException: Failed to extract /home/ubuntu/workspace/build-scripts/jobs/jdk15u/jdk15u-linux-ppc64le-openj9/transfer of 8 files
21:34:11  	at hudson.FilePath.readFromTar(FilePath.java:2661)
21:34:11  	at hudson.FilePath.copyRecursiveTo(FilePath.java:2439)
21:34:11  	at jenkins.model.StandardArtifactManager.archive(StandardArtifactManager.java:70)
21:34:11  	at hudson.tasks.ArtifactArchiver.perform(ArtifactArchiver.java:257)
21:34:11  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:116)
21:34:11  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
21:34:11  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
21:34:11  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
21:34:11  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
21:34:11  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:34:11  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:34:11  	at java.lang.Thread.run(Thread.java:748)
21:34:11  	Suppressed: java.util.concurrent.ExecutionException: hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected EOF
21:34:11  		at hudson.remoting.Request$1.get(Request.java:323)
21:34:11  		at hudson.remoting.Request$1.get(Request.java:239)
21:34:11  		at hudson.remoting.FutureAdapter.get(FutureAdapter.java:64)
21:34:11  		at hudson.FilePath.copyRecursiveTo(FilePath.java:2442)
21:34:11  		... 10 more
21:34:11  	Caused by: hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected EOF
21:34:11  		at hudson.remoting.Request.abort(Request.java:344)
21:34:11  		at hudson.remoting.Channel.terminate(Channel.java:1085)
21:34:11  		at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:94)
21:34:11  	Caused by: java.io.IOException: Unexpected EOF
21:34:11  		at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:99)
21:34:11  		at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
21:34:11  		at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
21:34:11  		at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
21:34:11  	Suppressed: java.io.IOException: Can not call launch on a dummy launcher.
21:34:11  		at hudson.Launcher$DummyLauncher.launch(Launcher.java:1072)
21:34:11  		at hudson.Launcher$ProcStarter.start(Launcher.java:508)
21:34:11  		at org.jenkinsci.plugins.docker.workflow.client.DockerClient.launch(DockerClient.java:301)
21:34:11  		at org.jenkinsci.plugins.docker.workflow.client.DockerClient.launch(DockerClient.java:282)
21:34:11  		at org.jenkinsci.plugins.docker.workflow.client.DockerClient.launch(DockerClient.java:279)
21:34:11  		at org.jenkinsci.plugins.docker.workflow.client.DockerClient.stop(DockerClient.java:174)
21:34:11  		at org.jenkinsci.plugins.docker.workflow.WithContainerStep.destroy(WithContainerStep.java:109)
21:34:11  		at org.jenkinsci.plugins.docker.workflow.WithContainerStep.access$400(WithContainerStep.java:76)
21:34:11  		at org.jenkinsci.plugins.docker.workflow.WithContainerStep$Callback.finished(WithContainerStep.java:391)
21:34:11  		at org.jenkinsci.plugins.workflow.steps.BodyExecutionCallback$TailCall.onFailure(BodyExecutionCallback.java:128)
21:34:11  		at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:361)
21:34:11  		at com.cloudbees.groovy.cps.impl.ThrowBlock$1.receive(ThrowBlock.java:68)
21:34:11  		at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
21:34:11  		at com.cloudbees.groovy.cps.Next.step(Next.java:83)
21:34:11  		at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
21:34:11  		at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
21:34:11  		at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
21:34:11  		at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
21:34:11  		at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
21:34:11  		at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
21:34:11  		at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
21:34:11  		at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
21:34:11  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
21:34:11  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
21:34:11  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
21:34:11  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
21:34:11  		at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
21:34:11  		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
21:34:11  		at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:136)
21:34:11  		at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
21:34:11  		at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
21:34:11  		... 5 more
21:34:11  Caused by: java.io.IOException: java.io.IOException: Unexpected EOF
21:34:11  	at hudson.remoting.FastPipedInputStream.read(FastPipedInputStream.java:170)
21:34:11  	at hudson.util.HeadBufferingStream.read(HeadBufferingStream.java:61)
21:34:11  	at com.jcraft.jzlib.InflaterInputStream.fill(InflaterInputStream.java:175)
21:34:11  	at com.jcraft.jzlib.InflaterInputStream.read(InflaterInputStream.java:106)
21:34:11  	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:639)
21:34:11  	at java.io.InputStream.read(InputStream.java:101)
21:34:11  	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314)
21:34:11  	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
21:34:11  	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
21:34:11  	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2246)
21:34:11  	at hudson.util.IOUtils.copy(IOUtils.java:43)
21:34:11  	at hudson.FilePath.readFromTar(FilePath.java:2651)
21:34:11  	... 11 more
21:34:11  Caused by: [CIRCULAR REFERENCE: java.io.IOException: Unexpected EOF]
21:34:11  
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
Finished: FAILURE

REST API
Jenkins 2.249.3
```

**Comment by M-Davies** [comment]
Hit this in a [JDK8/HS/x-linux](https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/924/console) and [JDK11/J9/x-linux](https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9/479/console) pr tester run early this morning/ late last night -> https://github.com/AdoptOpenJDK/openjdk-build/pull/2238#issuecomment-731573820

**Comment by sxa** [comment]
Interesting - don't think that's been seen on the main pipelines other than on pLinux. Nightlies did not obviously appear to be affected so we should se if it recurs. We had an issue previously with updates being scheduled mid way through a build but I thourhg we'd mitigated that.

**Comment by karianna** [comment]
Does the title need to reflect this is in PR builds only?

**Comment by sxa** [comment]
> Does the title need to reflect this is in PR builds only?

While Morgan has seen it in a PR build over the weekend (for X64 - maybe a one off?) the original report problem was on the nightlies as per the Andrew's original URL in this issue. Assuming dockerBuilds on all platforms will be reinstated, leaving this open with the existing title is the right thing to do.

**Comment by M-Davies** [comment]
JDK15 has been retired and no more instances of this issue appear to have been spotted. Closing for now unless this reoccurs...
