### ISSUE TITLE
build git clean -fdx #timeout=10 sometimes timing out

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2273]
```
03:31:06   > git clean -fdx # timeout=10
03:41:07  ERROR: Error fetching remote repo 'origin'
03:41:07  hudson.plugins.git.GitException: Failed to fetch from https://github.com/AdoptOpenJDK/openjdk-build.git
03:41:07  	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:996)
03:41:07  	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1237)
03:41:07  	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1297)
03:41:07  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
03:41:07  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
03:41:07  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
03:41:07  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
03:41:07  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
03:41:07  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03:41:07  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
03:41:07  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
03:41:07  	at java.lang.Thread.run(Thread.java:748)
03:41:07  Caused by: hudson.plugins.git.GitException: Command "git clean -fdx" returned status code 143:
```

On the successful builds it is noted the time taken to clean can be very close to 10minutes, eg: this successful build:
```
03:31:21   > git clean -fdx # timeout=10
03:40:15  Pruning obsolete local branches
```
=> about 9mins

**Comment by M-Davies** [comment]
Dup of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1553
