### ISSUE TITLE
adopt-openj9-1.8.0_275 produces SSL Exception errors for mysql:mysql-connector-java:5.1.43

### ISSUE THREAD

**Issue by Larkenx** [AdoptOpenJDK/openjdk-build#2295]
When starting up a Tomcat Spring Boot Java server that connects to a MySQL datasource via the 5.1.xx drivers, we get SSL errors. Is this a compatibility issue with these specific drivers and OpenJDK version? This works as intended when using Oracle JDK version (jdk1.8.0_112)but not OpenJDK 1.8.0_275

```
Tue Dec 08 14:23:36 EST 2020 WARN: Caught while disconnecting...

EXCEPTION STACK TRACE:



** BEGIN NESTED EXCEPTION ** 

javax.net.ssl.SSLException
MESSAGE: closing inbound before receiving peer's close_notify

STACKTRACE:

javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:311)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
	at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:637)
	at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:616)
	at com.mysql.jdbc.MysqlIO.quit(MysqlIO.java:2246)
	at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4234)
	at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1472)
	at org.apache.commons.dbcp.DelegatingConnection.close(DelegatingConnection.java:247)
	at org.apache.commons.dbcp.PoolableConnection.reallyClose(PoolableConnection.java:122)
	at org.apache.commons.dbcp.PoolableConnectionFactory.destroyObject(PoolableConnectionFactory.java:628)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1562)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
```

**Comment by Larkenx** [comment]
Bumping the MySQL driver to latest (8.0.22) resolved the SSL issues
