### ISSUE TITLE
Intermittent: IllegalStateException: No display name received from Xvfb within 10 seconds

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2368]
https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk11_hs_sanity.functional_ppc64le_linux/67/console
```
[Pipeline] wrap
18:25:22  $ Xvfb -displayfd 2 -screen 0 1024x768x24 -fbdir /home/jenkins/xvfb-67-..fbdir6437010955467642568
...
[Pipeline] End of Pipeline
java.lang.IllegalStateException: No display name received from Xvfb within 10 seconds
	at org.jenkinsci.plugins.xvfb.AutoDisplayNameFilterStream.getDisplayNumber(AutoDisplayNameFilterStream.java:77)
	at org.jenkinsci.plugins.xvfb.Xvfb.launchXvfb(Xvfb.java:605)
	at org.jenkinsci.plugins.xvfb.Xvfb.setUp(Xvfb.java:697)
	at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2.doStart(CoreWrapperStep.java:116)
	at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2$$Lambda$593/000000000000000000.run(Unknown Source)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution$$Lambda$594/000000000000000000.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)
```

**Comment by andrew-m-leonard** [comment]
https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk11_hs_extended.functional_ppc64le_linux/67/consoleFull

**Comment by andrew-m-leonard** [comment]
Nodes:
- test-osuosl-ubuntu1804-ppc64le-2

**Comment by andrew-m-leonard** [comment]
The problem is related to the Xvfb plugin AutoDisplayNameFilterStream, which has an inbuilt 10second timeout on getDisplayName(), note this has been extended in Xvfb 1.1.4 to 30seconds due to this issue: https://github.com/jenkinsci/xvfb-plugin/commit/070b8d86861d9dbe2629ddcdefa8021362362ed6
However, 1.1.4 is not available...
We can however add a wait timeout to the Xvfb construction: 
```
timeout (optional)
A timeout of given seconds to wait before returning control to the job, this allows Xvfb to start before there is a need for it. By default set to 0, not to delay the build, since it usualy takes just a few seconds for Xvfb to start, and outputting to display is not the first thing a job does. 
```
This pauses here: https://github.com/jenkinsci/xvfb-plugin/blob/c8a89302e42663e3cb03fd564ac2b675e6a07892/src/main/java/org/jenkinsci/plugins/xvfb/Xvfb.java#L592
which is then prior to getDisplayName().

I will create an openjdk-tests PR to add this timeout here: https://github.com/AdoptOpenJDK/openjdk-tests/blob/20a13c20e5a1d31506a7fb6e41bf86d95c7bdac5/buildenv/jenkins/JenkinsfileBase#L563
 @smlambert fyi

**Comment by andrew-m-leonard** [comment]
Fixed by: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2149
