### ISSUE TITLE
AIX port 9999 in use hang

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2375]
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_extended.functional_ppc64_aix/60/console
```
04:27:25  ===============================================
04:27:25  Running test testOpenJ9DiagnosticsMXBean_0 ...
04:27:25  ===============================================
04:27:25  testOpenJ9DiagnosticsMXBean_0 Start Time: Tue Jan 12 22:27:19 2021 Epoch Time (ms): 1610512039320
04:27:25  "/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
04:27:25  JVMSHRC005I No shared class caches available
04:27:25  JVMSHRC005I No shared class caches available
04:27:25  cache cleanup done
04:27:25  variation: NoOptions
04:27:25  JVM_OPTIONS:  
04:27:25  { itercnt=1; \
04:27:25  mkdir -p "/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/test_output_16105090271999/testOpenJ9DiagnosticsMXBean_0"; \
04:27:25  cd "/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/test_output_16105090271999/testOpenJ9DiagnosticsMXBean_0"; \
04:27:25  export LIBPATH="/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdkbinary/openjdk-test-image/openj9:/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/../lib/compressedrefs:/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/../lib/j9vm:/opt/freeware/lib"; \
04:27:25  "/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/java"   \
04:27:25  -Xdump:dynamic \
04:27:25  -Dremote.server.option="  -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false" \
04:27:25  -cp "/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar" \
04:27:25  org.testng.TestNG -d "/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/test_output_16105090271999/testOpenJ9DiagnosticsMXBean_0" "/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/testng.xml" \
04:27:25  -testnames testOpenJ9DiagnosticsMXBean \
04:27:25  -groups level.extended \
04:27:25  -excludegroups d.*.aix_ppc-64_cmprssptrs,d.*.arch.ppc,d.*.os.aix,d.*.bits.64,d.*.generic-all; \
04:27:25  if [ $? -eq 0 ] ; then echo ""; echo "testOpenJ9DiagnosticsMXBean_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/..;  else echo ""; echo "testOpenJ9DiagnosticsMXBean_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/test_output_16105090271999/TestTargetResult";
04:27:25  [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TestConfig/resources/excludes/latest_exclude_15.txt
04:27:25  ...
04:27:25  ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
04:27:25  ...
04:27:25  
04:27:25  [TestOpenJ9DiagnosticsMXBean] [INFO] Starting Remote Server to Monitor!
04:27:25  [TestOpenJ9DiagnosticsMXBean] [INFO] [/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/java, -Xdump:dynamic, -classpath, /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar, -Dcom.sun.management.jmxremote.port=9999, -Dcom.sun.management.jmxremote.authenticate=false, -Dcom.sun.management.jmxremote.ssl=false, -Djava.lock.file=/tmp/tmp11963128837353475326.lock, org.openj9.test.java.lang.management.RemoteProcess]
04:27:25  Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 9999; nested exception is: 
04:27:25  	java.net.BindException: The socket name is already in use.
04:27:25  jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 9999; nested exception is: 
04:27:25  	java.net.BindException: The socket name is already in use.
04:27:25  	at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:493)
04:27:25  	at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:447)
04:27:25  	at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:599)
04:27:25  	at java.base/java.lang.System.startSNMPAgent(Native Method)
04:27:25  	at java.base/java.lang.Thread.completeInitialization(Thread.java:184)
04:27:25  	at java.base/java.lang.J9VMInternals.completeInitialization(J9VMInternals.java:74)
04:27:25  Caused by: java.rmi.server.ExportException: Port already in use: 9999; nested exception is: 
04:27:25  	java.net.BindException: The socket name is already in use.
04:27:25  	at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:346)
04:27:25  	at java.rmi/sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:243)
04:27:25  	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:412)
04:27:25  	at java.rmi/sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
04:27:25  	at java.rmi/sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:234)
04:27:25  	at java.rmi/sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:220)
04:27:25  	at java.rmi/sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:180)
04:27:25  	at jdk.management.agent/sun.management.jmxremote.SingleEntryRegistry.<init>(SingleEntryRegistry.java:49)
04:27:25  	at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:860)
04:27:25  	at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:481)
04:27:25  	... 5 more
04:27:25  Caused by: java.net.BindException: The socket name is already in use.
04:27:25  	at java.base/sun.nio.ch.Net.bind0(Native Method)
04:27:25  	at java.base/sun.nio.ch.Net.bind(Net.java:550)
04:27:25  	at java.base/sun.nio.ch.Net.bind(Net.java:539)
04:27:25  	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
04:27:25  	at java.base/java.net.ServerSocket.bind(ServerSocket.java:396)
04:27:25  	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:282)
04:27:25  	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:173)
04:27:25  	at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createServerSocket(TCPDirectSocketFactory.java:45)
04:27:25  	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:670)
04:27:25  	at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:335)
04:27:25  	... 14 more
04:27:25  Exception in thread "main" java/lang/RuntimeException: jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 9999; nested exception is: 
04:27:25  	java.net.BindException: The socket name is already in use.
04:27:25  	at jdk/internal/agent/Agent.error (jdk.management.agent@15.0.1/Agent.java:669)
04:27:25  	at jdk/internal/agent/Agent.startAgent (jdk.management.agent@15.0.1/Agent.java:454)
04:27:25  	at jdk/internal/agent/Agent.startAgent (jdk.management.agent@15.0.1/Agent.java:599)
04:27:25  	at java/lang/System.startSNMPAgent (java.base@9/NativeMethod:4294967295)
04:27:25  	at java/lang/Thread.completeInitialization (java.base@9/Thread.java:184)
04:27:25  	at java/lang/J9VMInternals.completeInitialization (java.base@9/J9VMInternals.java:74)

REST API
Jenkins 2.263.1
```
test-osuosl-aix72-ppc64-2

**Comment by andrew-m-leonard** [comment]
possibly one of these pre hung processes on this machine:
```
03:22:29  PROCESSCATCH: Java processes which are currently on the machine:
[Pipeline] sh
03:22:31  + ps -fu jenkins
03:22:31  + grep java
03:22:31  + egrep -v remoting.jar|agent.jar|grep
03:22:31   jenkins  9240994 16646652   0   Jan 06      -  8:05 /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/jre/bin/java -Xdump:dynamic -classpath /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.lock.file=/tmp/tmp8565343107971863323.lock org.openj9.test.java.lang.management.RemoteProcess
03:22:31   jenkins 16646652        1   0   Jan 06      -  0:56 /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/java -Xdump:dynamic -Dremote.server.option=  -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -cp /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar org.testng.TestNG -d /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/test_output_16099498377217/testOpenJ9DiagnosticsMXBean_0 /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/testng.xml -testnames testOpenJ9DiagnosticsMXBean -groups level.extended -excludegroups d.*.aix_ppc-64_cmprssptrs,d.*.arch.ppc,d.*.os.aix,d.*.bits.64,d.*.generic-all
03:22:31   jenkins 19071324        1   0   Jan 09      -  6:51 /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix/openjdkbinary/j2sdk-image/bin/java -Xgcpolicy:gencon -Xgc:concurrentScavenge -classpath /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix/jvmtest/system/stf/stf.load/bin:/home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix/jvmtest/system/stf/stf.core/bin:/home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix/jvmtest/system/systemtest_prereqs/log4j-2.13.3/log4j-api-2.13.3.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix/jvmtest/system/systemtest_prereqs/log4j-2.13.3/log4j-core-2.13.3.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix/jvmtest/system/systemtest_prereqs/junit-4.12/junit-4.12.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix/jvmtest/system/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix/jvmtest/system/openj9-systemtest/openj9.test.daa/bin net.adoptopenjdk.loadTest.LoadTest -resultsDir /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix/openjdk-tests/TKG/test_output_16101979274832/DaaLoadTest_all_ConcurrentScavenge_0/20210109-071336-DaaLoadTest/results -resultsPrefix 1.DLT. -dumpRequested false -reportFailureLimit 1 -abortAtFailureLimit 10 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.daa.threadCount 14 -suite.daa.totalNumberTests 7200 -suite.daa.inventoryFile /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix/openjdk-tests/TKG/test_output_16101979274832/DaaLoadTest_all_ConcurrentScavenge_0/20210109-071336-DaaLoadTest/results/1.DLT.inventory/openj9.test.load/config/inventories/daa/daaAll.xml -suite.daa.inventoryExcludeFile none -suite.daa.selection random -suite.daa.seed -1 -suite.daa.repeatCount 1 -suite.daa.thinkingTime 0ms..0ms
```

**Comment by andrew-m-leonard** [comment]
Both these are already using port 9999:
```
03:22:31   jenkins  9240994 16646652   0   Jan 06      -  8:05 /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/jre/bin/java -Xdump:dynamic -classpath /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.lock.file=/tmp/tmp8565343107971863323.lock org.openj9.test.java.lang.management.RemoteProcess
03:22:31   jenkins 16646652        1   0   Jan 06      -  0:56 /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/java -Xdump:dynamic -Dremote.server.option=  -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -cp /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar org.testng.TestNG -d /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/test_output_16099498377217/testOpenJ9DiagnosticsMXBean_0 /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/testng.xml -testnames testOpenJ9DiagnosticsMXBean -groups level.extended -excludegroups d.*.aix_ppc-64_cmprssptrs,d.*.arch.ppc,d.*.os.aix,d.*.bits.64,d.*.generic-all

```
They are relations, parent 16646652
This was on Jan6, wondering if the test job Aborted due to timeout, as there is at least 7hours execution time between the start times?

**Comment by andrew-m-leonard** [comment]
Testcase = testOpenJ9DiagnosticsMXBean

**Comment by andrew-m-leonard** [comment]
@sxa wondering if we should implement the "kill" logic for unix as per Windows ?

**Comment by andrew-m-leonard** [comment]
Hung processes also on https://ci.adoptopenjdk.net/computer/test-osuosl-aix72-ppc64-1/script
possibly different testcase:
```
 jenkins 29819162        1  99 16:04:41      - 383:43 /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/openjdkbinary/j2sdk-image/bin/java -Xgcpolicy:gencon -Xgc:concurrentScavenge -classpath /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/jvmtest/system/stf/stf.load/bin:/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/jvmtest/system/stf/stf.core/bin:/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/jvmtest/system/systemtest_prereqs/log4j-2.13.3/log4j-api-2.13.3.jar:/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/jvmtest/system/systemtest_prereqs/log4j-2.13.3/log4j-core-2.13.3.jar:/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/jvmtest/system/systemtest_prereqs/junit-4.12/junit-4.12.jar:/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/jvmtest/system/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar:/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/jvmtest/system/openj9-systemtest/openj9.test.daa/bin net.adoptopenjdk.loadTest.LoadTest -resultsDir /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/openjdk-tests/TKG/test_output_16104889309508/DaaLoadTest_all_ConcurrentScavenge_0/20210112-160436-DaaLoadTest/results -resultsPrefix 1.DLT. -dumpRequested false -reportFailureLimit 1 -abortAtFailureLimit 10 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.daa.threadCount 18 -suite.daa.totalNumberTests 7200 -suite.daa.inventoryFile /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix/openjdk-tests/TKG/test_output_16104889309508/DaaLoadTest_all_ConcurrentScavenge_0/20210112-160436-DaaLoadTest/results/1.DLT.inventory/openj9.test.load/config/inventories/daa/daaAll.xml -suite.daa.inventoryExcludeFile none -suite.daa.selection random -suite.daa.seed -1 -suite.daa.repeatCount 1 -suite.daa.thinkingTime 0ms..0ms
    root 29950352 32375116   0 02:43:06      -  0:00 sh -c /usr/sbin/blockip -x continue >> /var/blockip/log/blockip.log 2>&1
    root 30015842 32375116   0 02:31:09      -  0:00 sh -c /usr/sbin/blockip -x continue >> /var/blockip/log/blockip.log 2>&1
 jenkins 30867820 32768316   1 02:44:49      -  0:00 ps -ef
    root 32243972 10748254   0   Jan 11      -  0:00 sshd: jenkins [priv]
 jenkins 32309672        1   0   Dec 26      - 24:24 /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/java -Xcompressedrefs -Xjit -Xgcpolicy:gencon -DPATHSEP=/ -DCPDL=: -DRUN_SCRIPT=sh -DPROPS_DIR=props_unix -DSCRIPT_SUFFIX=.sh -DEXECUTABLE_SUFFIX= -DJAVA_EXE="/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -DJAVA_HOME=/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdkbinary/j2sdk-image -DSCMODE=204 -DJVM_TEST_ROOT=/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest -DUTILSJAR=/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/utils/utils.jar -jar /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_tester/cmdlinetester.jar -config /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-2.xml -xids all,aix_ppc-64_cr,,15 -plats all,aix_ppc-64_cr, -xlist /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/shareClassTests/SCCMLTests/exclude.xml -nonZeroExitWhenError -outputLimit 300
```

**Comment by andrew-m-leonard** [comment]
Is it a coincidence all the hangs have been on test-osuosl nodes?

**Comment by sxa** [comment]
> @sxa wondering if we should implement the "kill" logic for unix as per Windows ?

We should run grinders to identify which part is hanging it then decide on a fix. Just killing stuff runs you a serious risk of just masking underlying problems.

**Comment by andrew-m-leonard** [comment]
> > @sxa wondering if we should implement the "kill" logic for unix as per Windows ?
> 
> We should run grinders to identify which part is hanging it then decide on a fix. Just killing stuff runs you a serious risk of just masking underlying problems.

Not sure what leaving the Process there achieves other than future build headaches. The job gets Aborted anyway and testcase failure, so it's not as if it is not going to get seen. Some of these hung processes date back over a week, so it obviously did not achieve anything? If we had had the time to triage all the tests we would have come across the failed and Aborted tests where they hung on 6th Jan.

**Comment by sxa** [comment]
So my comment would be why isn't this at the top of the triage priority list if it's having such a visible effect on a regular basis? My point is that sticking kills in makes it easier to not see this as what it should be - a high priority issue to triage and debug.

**Comment by karianna** [comment]
Should this be in the test repo?

**Comment by andrew-m-leonard** [comment]
I've not seen this for over a week now, I believe resolving the extended.functional excessive timeouts causing hung processes has probably resolved this.
