### ISSUE TITLE
jmc-build job hung on linux installer node: build-scaleway-ubuntu1604-x64-1

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2387]
https://ci.adoptopenjdk.net/job/jmc-build/job/master/248/console
```
[INFO] Command line:
	[/home/jenkins/tools/hudson.model.JDK/JDK11/jdk-11.0.8+10/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=linux, -Dosgi.ws=gtk, -Dosgi.arch=x86_64, -XX:+IgnoreUnrecognizedVMOptions, -XX:+UseG1GC, -XX:+FlightRecorder, -Djava.net.preferIPv4Stack=true, -Djdk.attach.allowAttachSelf=true, --add-exports=java.xml/com.sun.org.apache.xerces.internal.parsers=ALL-UNNAMED, --add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED, --add-exports=java.management/sun.management=ALL-UNNAMED, --add-exports=java.management/sun.management.counter.perf=ALL-UNNAMED, --add-exports=jdk.management.agent/jdk.internal.agent=ALL-UNNAMED, --add-exports=jdk.attach/sun.tools.attach=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.windows=ALL-UNNAMED, --add-opens=java.base/java.net=ALL-UNNAMED, --add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.X11=ALL-UNNAMED, -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.8.3/org.jacoco.agent-0.8.3-runtime.jar=destfile=/home/jenkins/workspace/jmc-build_master/application/uitests/org.openjdk.jmc.browser.uitest/target/jacoco.exec, -Dosgi.clean=true, -jar, /home/jenkins/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.5.800.v20200727-1323/org.eclipse.equinox.launcher-1.5.800.v20200727-1323.jar, -data, /home/jenkins/workspace/jmc-build_master/application/uitests/org.openjdk.jmc.browser.uitest/target/work/data, -install, /home/jenkins/workspace/jmc-build_master/application/uitests/org.openjdk.jmc.browser.uitest/target/work, -configuration, /home/jenkins/workspace/jmc-build_master/application/uitests/org.openjdk.jmc.browser.uitest/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.uitest, -testproperties, /home/jenkins/workspace/jmc-build_master/application/uitests/org.openjdk.jmc.browser.uitest/target/surefire.properties, -testApplication, org.openjdk.jmc.rcp.application.app, -product, org.openjdk.jmc.rcp.application.product, -nouithread, -nl, en, -consoleLog, --launcher.appendVmargs]
WARNING: package sun.awt.windows not in java.desktop
!SESSION 2021-01-16 03:36:02.232 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.8
java.vendor=AdoptOpenJDK
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en
Framework arguments:  -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties /home/jenkins/workspace/jmc-build_master/application/uitests/org.openjdk.jmc.browser.uitest/target/surefire.properties -testApplication org.openjdk.jmc.rcp.application.app -product org.openjdk.jmc.rcp.application.product -nouithread
Command-line arguments:  -data /home/jenkins/workspace/jmc-build_master/application/uitests/org.openjdk.jmc.browser.uitest/target/work/data -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties /home/jenkins/workspace/jmc-build_master/application/uitests/org.openjdk.jmc.browser.uitest/target/surefire.properties -testApplication org.openjdk.jmc.rcp.application.app -product org.openjdk.jmc.rcp.application.product -nouithread -consoleLog

!ENTRY org.eclipse.ecf.provider.filetransfer.httpclient45.win32 4 0 2021-01-16 03:36:09.806
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.ecf.provider.filetransfer.httpclient45.win32 [364]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(osgi.os=win32)"
  Unresolved requirement: Import-Package: org.apache.http.impl.auth.win; version="[4.5.0,5.0.0)"
    -> Export-Package: org.apache.http.impl.auth.win; bundle-symbolic-name="org.apache.httpcomponents.httpclient.win"; bundle-version="4.5.10.v20200113-2105"; version="4.5.10"; x-internal:="true"; uses:="org.apache.http,org.apache.http.auth,org.apache.http.client,org.apache.http.impl.auth,org.apache.http.protocol,org.apache.http.util"
       org.apache.httpcomponents.httpclient.win [36]
         Unresolved requirement: Require-Capability: eclipse.platform; filter:="(osgi.os=win32)"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Launching application org.openjdk.jmc.rcp.application.app...
***WARNING: GTK+ version too old (micro mismatch)
***WARNING: SWT requires GTK 3.20.0
***WARNING: Detected: 3.18.9

(JDK Mission Control:10684): Gtk-WARNING **: Theme parsing error: <data>:7:18: '-gtk-key-bindings' is not a valid property name

(JDK Mission Control:10684): Gtk-WARNING **: Theme parsing error: <data>:31:11: 'min-height' is not a valid property name

!ENTRY org.eclipse.jface 2 0 2021-01-16 03:36:19.425
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2021-01-16 03:36:19.426
!MESSAGE A conflict occurred for CTRL+3:
Binding(CTRL+3,
	ParameterizedCommand(Command(org.eclipse.ui.window.quickAccess,Find Actions,
		Quickly access UI elements,
		Category(org.eclipse.ui.category.window,Window,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@643a3a79,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+3,
	ParameterizedCommand(Command(org.eclipse.ui.window.quickAccess,Find Actions,
		Quickly access UI elements,
		Category(org.eclipse.ui.category.window,Window,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@643a3a79,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
SWT Webkit: Warning, You are using an old version of webkitgtk. (pre 2.4) BrowserFunction functionality will not be avaliable
SWT WebKit: error initializing DBus server, dBusServer == 0
Missing CEF binaries for Chromium Browser. Extract CEF binaries to /home/jenkins/.swt/lib/linux/x86_64/chromium-3071 (java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	Can't load library: /home/jenkins/.swt/lib/linux/x86_64/chromium-3071/libcef.so
	Can't load library: /home/jenkins/.swt/lib/linux/x86_64//home/jenkins/.swt/lib/linux/x86_64/chromium-3071/libcef.so
)
Running org.openjdk.jmc.browser.uitest.ConnectionExportImportTest
Jan 16, 2021 3:36:26 AM org.openjdk.jmc.rcp.application.ApplicationWorkbenchAdvisor execute
WARNING: Unknown command 'testproperties'. Error found at row 0, from position 0 to 13
Jan 16, 2021 3:36:26 AM org.openjdk.jmc.rcp.application.ApplicationWorkbenchAdvisor execute
WARNING: Unknown command 'testApplication'. Error found at row 0, from position 0 to 14
Jan 16, 2021 3:36:26 AM org.openjdk.jmc.rcp.application.ApplicationWorkbenchAdvisor execute
WARNING: Unknown command 'nouithread'. Error found at row 0, from position 0 to 9
Loading jemmy properties from /home/jenkins/.jemmy.properties
Property file /home/jenkins/.jemmy.properties does not exists. Ignoring.
Input factory set to org.jemmy.input.awt.AWTRobotInputFactory[otherVM=false, mouseSmoothness=2147483647]
ImageCapturer set to org.jemmy.image.awt.AWTRobotCapturer@16dd663
Input factory set to org.jemmy.input.awt.AWTRobotInputFactory[otherVM=false, mouseSmoothness=2147483647]
Input factory set to org.jemmy.input.awt.AWTRobotInputFactory[otherVM=false, mouseSmoothness=2147483647]
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

Retrying menu operation to open dialog "Preferences" (at menu path: [&Window, &Preferences])
Retrying menu operation to open dialog "Preferences" (at menu path: [&Window, &Preferences])
Action 'typing text "Connection0"' failed with the following exception: 
org.jemmy.TimeoutExpiredException: State 'text() equals 'Connection0', text() = 'Connectionnn0'' has not been reached in 1000 milliseconds
	at org.jemmy.timing.Waiter.ensureState(Waiter.java:85)
	at org.jemmy.input.TextImpl$1.run(TextImpl.java:78)
	at org.jemmy.action.Action.execute(Action.java:50)
	at org.jemmy.action.ActionQueue$ActionRecord.execute(ActionQueue.java:167)
	at org.jemmy.action.ActionQueue$1.run(ActionQueue.java:65)
	at java.base/java.lang.Thread.run(Thread.java:834)
Action 'typing text "password"' failed with the following exception: 
org.jemmy.TimeoutExpiredException: State 'text() equals 'password', text() = 'passssword'' has not been reached in 1000 milliseconds
	at org.jemmy.timing.Waiter.ensureState(Waiter.java:85)
	at org.jemmy.input.TextImpl$1.run(TextImpl.java:78)
	at org.jemmy.action.Action.execute(Action.java:50)
	at org.jemmy.action.ActionQueue$ActionRecord.execute(ActionQueue.java:167)
	at org.jemmy.action.ActionQueue$1.run(ActionQueue.java:65)
	at java.base/java.lang.Thread.run(Thread.java:834)
Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 122.419 s <<< FAILURE! - in org.openjdk.jmc.browser.uitest.ConnectionExportImportTest
testImportNonExistantFile(org.openjdk.jmc.browser.uitest.ConnectionExportImportTest)  Time elapsed: 23.382 s
testExportImport(org.openjdk.jmc.browser.uitest.ConnectionExportImportTest)  Time elapsed: 19.997 s  <<< ERROR!
org.jemmy.JemmyException: Action 'typing text "Connection0"' invoked through ActionQueue failed
	at org.openjdk.jmc.browser.uitest.ConnectionExportImportTest.testExportImport(ConnectionExportImportTest.java:93)
Caused by: org.jemmy.TimeoutExpiredException: State 'text() equals 'Connection0', text() = 'Connectionnn0'' has not been reached in 1000 milliseconds

testSetMasterPassword(org.openjdk.jmc.browser.uitest.ConnectionExportImportTest)  Time elapsed: 36.17 s  <<< ERROR!
org.jemmy.JemmyException: Action 'typing text "password"' invoked through ActionQueue failed
	at org.openjdk.jmc.browser.uitest.ConnectionExportImportTest.testSetMasterPassword(ConnectionExportImportTest.java:135)
Caused by: org.jemmy.TimeoutExpiredException: State 'text() equals 'password', text() = 'passssword'' has not been reached in 1000 milliseconds

Running org.openjdk.jmc.browser.uitest.CustomConnectionsTest
Action 'typing text "7777"' failed with the following exception: 
org.jemmy.TimeoutExpiredException: State 'text() equals '7777', text() = '0'' has not been reached in 1000 milliseconds
	at org.jemmy.timing.Waiter.ensureState(Waiter.java:85)
	at org.jemmy.input.TextImpl$1.run(TextImpl.java:78)
	at org.jemmy.action.Action.execute(Action.java:50)
	at org.jemmy.action.ActionQueue$ActionRecord.execute(ActionQueue.java:167)
	at org.jemmy.action.ActionQueue$1.run(ActionQueue.java:65)
	at java.base/java.lang.Thread.run(Thread.java:834)
Action 'typing text "7777"' failed with the following exception: 
org.jemmy.TimeoutExpiredException: State 'text() equals '7777', text() = '0'' has not been reached in 1000 milliseconds
	at org.jemmy.timing.Waiter.ensureState(Waiter.java:85)
	at org.jemmy.input.TextImpl$1.run(TextImpl.java:78)
	at org.jemmy.action.Action.execute(Action.java:50)
	at org.jemmy.action.ActionQueue$ActionRecord.execute(ActionQueue.java:167)
	at org.jemmy.action.ActionQueue$1.run(ActionQueue.java:65)
	at java.base/java.lang.Thread.run(Thread.java:834)
Action 'typing text "Valid Connection"' failed with the following exception: 
org.jemmy.TimeoutExpiredException: State 'text() equals 'Valid Connection', text() = 'PasswordConnection'' has not been reached in 1000 milliseconds
	at org.jemmy.timing.Waiter.ensureState(Waiter.java:85)
	at org.jemmy.input.TextImpl$1.run(TextImpl.java:78)
	at org.jemmy.action.Action.execute(Action.java:50)
	at org.jemmy.action.ActionQueue$ActionRecord.execute(ActionQueue.java:167)
	at org.jemmy.action.ActionQueue$1.run(ActionQueue.java:65)
	at java.base/java.lang.Thread.run(Thread.java:834)
Action 'typing text "7777"' failed with the following exception: 
org.jemmy.TimeoutExpiredException: State 'text() equals '7777', text() = '0'' has not been reached in 1000 milliseconds
	at org.jemmy.timing.Waiter.ensureState(Waiter.java:85)
	at org.jemmy.input.TextImpl$1.run(TextImpl.java:78)
	at org.jemmy.action.Action.execute(Action.java:50)
	at org.jemmy.action.ActionQueue$ActionRecord.execute(ActionQueue.java:167)
	at org.jemmy.action.ActionQueue$1.run(ActionQueue.java:65)
	at java.base/java.lang.Thread.run(Thread.java:834)
Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 183.77 s <<< FAILURE! - in org.openjdk.jmc.browser.uitest.CustomConnectionsTest
renameConnection(org.openjdk.jmc.browser.uitest.CustomConnectionsTest)  Time elapsed: 32.094 s  <<< ERROR!
org.jemmy.JemmyException: Action 'typing text "7777"' invoked through ActionQueue failed
	at org.openjdk.jmc.browser.uitest.CustomConnectionsTest.renameConnection(CustomConnectionsTest.java:104)
Caused by: org.jemmy.TimeoutExpiredException: State 'text() equals '7777', text() = '0'' has not been reached in 1000 milliseconds

renameFolder(org.openjdk.jmc.browser.uitest.CustomConnectionsTest)  Time elapsed: 11.425 s  <<< ERROR!
org.jemmy.TimeoutExpiredException: State 'Waiting for 1 org.eclipse.swt.widgets.Shell controls to be found adhering to Text = New Folder' has not been reached in 10000 milliseconds
	at org.openjdk.jmc.browser.uitest.CustomConnectionsTest.renameFolder(CustomConnectionsTest.java:72)

nestedFoldersConnections(org.openjdk.jmc.browser.uitest.CustomConnectionsTest)  Time elapsed: 11.038 s  <<< ERROR!
org.jemmy.TimeoutExpiredException: State 'Waiting for 1 org.eclipse.swt.widgets.Shell controls to be found adhering to Text = New Folder' has not been reached in 10000 milliseconds
	at org.openjdk.jmc.browser.uitest.CustomConnectionsTest.nestedFoldersConnections(CustomConnectionsTest.java:79)

editConnection(org.openjdk.jmc.browser.uitest.CustomConnectionsTest)  Time elapsed: 68.817 s  <<< ERROR!
org.jemmy.JemmyException: Action 'typing text "7777"' invoked through ActionQueue failed
	at org.openjdk.jmc.browser.uitest.CustomConnectionsTest.editConnection(CustomConnectionsTest.java:122)
Caused by: org.jemmy.TimeoutExpiredException: State 'text() equals '7777', text() = '0'' has not been reached in 1000 milliseconds

validConnection(org.openjdk.jmc.browser.uitest.CustomConnectionsTest)  Time elapsed: 32.56 s  <<< ERROR!
org.jemmy.JemmyException: Action 'typing text "Valid Connection"' invoked through ActionQueue failed
	at org.openjdk.jmc.browser.uitest.CustomConnectionsTest.validConnection(CustomConnectionsTest.java:96)
Caused by: org.jemmy.TimeoutExpiredException: State 'text() equals 'Valid Connection', text() = 'PasswordConnection'' has not been reached in 1000 milliseconds

invalidConnection(org.openjdk.jmc.browser.uitest.CustomConnectionsTest)  Time elapsed: 15.346 s  <<< ERROR!
org.jemmy.JemmyException: Action 'typing text "7777"' invoked through ActionQueue failed
	at org.openjdk.jmc.browser.uitest.CustomConnectionsTest.invalidConnection(CustomConnectionsTest.java:113)
Caused by: org.jemmy.TimeoutExpiredException: State 'text() equals '7777', text() = '0'' has not been reached in 1000 milliseconds

createNewFolder(org.openjdk.jmc.browser.uitest.CustomConnectionsTest)  Time elapsed: 11.551 s  <<< ERROR!
org.jemmy.TimeoutExpiredException: State 'Waiting for 1 org.eclipse.swt.widgets.Shell controls to be found adhering to Text = New Folder' has not been reached in 10000 milliseconds
	at org.openjdk.jmc.browser.uitest.CustomConnectionsTest.createNewFolder(CustomConnectionsTest.java:66)

Running org.openjdk.jmc.browser.uitest.jvmcompat.LocalConnectionNamingTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.809 s - in org.openjdk.jmc.browser.uitest.jvmcompat.LocalConnectionNamingTest
verifyConnectionDialog(org.openjdk.jmc.browser.uitest.jvmcompat.LocalConnectionNamingTest) skipped
Running org.openjdk.jmc.browser.uitest.jvmcompat.ConnectionMessageTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.94 s - in org.openjdk.jmc.browser.uitest.jvmcompat.ConnectionMessageTest
verifyConnectionDialog(org.openjdk.jmc.browser.uitest.jvmcompat.ConnectionMessageTest) skipped

Results:

Errors: 
  ConnectionExportImportTest.testExportImport:93 » Jemmy Action 'typing text "Co...
  ConnectionExportImportTest.testSetMasterPassword:135 » Jemmy Action 'typing te...
  CustomConnectionsTest.createNewFolder:66 » TimeoutExpired State 'Waiting for 1...
  CustomConnectionsTest.editConnection:122 » Jemmy Action 'typing text "7777"' i...
  CustomConnectionsTest.invalidConnection:113 » Jemmy Action 'typing text "7777"...
  CustomConnectionsTest.nestedFoldersConnections:79 » TimeoutExpired State 'Wait...
  CustomConnectionsTest.renameConnection:104 » Jemmy Action 'typing text "7777"'...
  CustomConnectionsTest.renameFolder:72 » TimeoutExpired State 'Waiting for 1 or...
  CustomConnectionsTest.validConnection:96 » Jemmy Action 'typing text "Valid Co...

Tests run: 12, Failures: 0, Errors: 9, Skipped: 2
```

**Comment by andrew-m-leonard** [comment]
Hung again: https://ci.adoptopenjdk.net/job/jmc-build/job/master/250/console

**Comment by andrew-m-leonard** [comment]
This job is tied to the only "fpm" node (build-scaleway-ubuntu1604-x64-1) for create_installer_linux, so if it hangs on this node it blocks all pipelines...
Can we tie this job to a different node? https://github.com/AdoptOpenJDK/openjdk-jmc-overrides/blob/19296dd5160f593863bddb2dfab5cc82d34d79a9/Jenkinsfile#L1
@reinhapa @karianna

**Comment by reinhapa** [comment]
Running the build using the `x64&&linux&&ci.role.test` node does run but also emits the following warnings about older GTK version:
```
***WARNING: GTK+ version too old (micro mismatch)
***WARNING: SWT requires GTK 3.20.0
***WARNING: Detected: 3.18.9
```
Further there seem to be a newer SWT Webkit to be required:
```
SWT Webkit: Warning, You are using an old version of webkitgtk. (pre 2.4) BrowserFunction functionality will not be avaliable
```
For now, I will switch to the new node configuration in a first step as the result at least does not getting worse.

**Comment by sxa** [comment]
OK - mentioning GTK+ reminded me that this is also listed in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/932 (Although the last message on it was saying it didn't work on that box!) 

@reinhapa Have you got a link to the job you ran using that label? If I can take a look I can have a think about the best way to get something suitable onto a set of machines for you

**Comment by reinhapa** [comment]
@sxa I finally got around to move all JMC builds over to build nodes using the `x64&&linux&&ci.role.test` label. Now I got only the problem that for the `7.x.x` build the mercurial SCM tool is needed and not available on those nodes. Is it possible to add that one?

**Comment by reinhapa** [comment]
closed as the build is moved to github actions
