### ISSUE TITLE
SAP JVM: testFailure: testStress(net.adoptopenjdk.test.concurrent.ConcurrentSkipListMapTest): null java.util.NoSuchElementException

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#277]
From Volker at SAP

I'm not sure how to reproduce this error?

I've followed the instructions at https://github.com/AdoptOpenJDK/openjdk-systemtest and set `JAVA_HOME` to a `SapMachine 10-ea+46-sapmachine-2` downloaded from https://sap.github.io/SapMachine/

I can successfully build the "openjdk-systemtest" (step 6 in the readme) but when I execute the tests (i.e. "make test") I get the following error:

```
testStarted : testStress(net.adoptopenjdk.test.concurrent.ConcurrentSkipListMapTest)
testFailure: testStress(net.adoptopenjdk.test.concurrent.ConcurrentSkipListMapTest): null
java.util.NoSuchElementException
        at java.base/java.util.concurrent.ConcurrentSkipListMap$KeyIterator.next(ConcurrentSkipListMap.java:2135)
        at net.adoptopenjdk.test.concurrent.ConcurrentSkipListMapTest.testStress(ConcurrentSkipListMapTest.java:343)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:129)
        at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
testFinished: testStress(net.adoptopenjdk.test.concurrent.ConcurrentSkipListMapTest)

JUnit Test Results for: net.adoptopenjdk.test.concurrent.ConcurrentSkipListMapTest
  Ran    : 2
  Passed : 1
  Failed : 1
  Ignored: 0
  Result : FAILED
```
The same problem happens with a vanilla OpenJDK 10 as well.

Can you please advise how I can reproduce the problem?

**Comment by karianna** [comment]
Mesbah replied with:

Hi Volker,
The issue is seen during the building phase of system tests, where it tries to build the Mauve classes and fails as CORBA classes are not found. From your comment above, it appears that you were able to successfully build the sytstem-test source-- which means you have already gone past the point where the failure occurs (i.o.t., the test failure you reported is unrelated to the issue here).

Could you please post the build output that you saw while building systemtest with your SDK?

How is the SDK you used different than the SDK used in Adopt where the failure is seen? (We are using: https://ci.adoptopenjdk.net/job/openjdk10_sap_build_x86-64_linux/lastSuccessfulBuild/artifact/OpenJDK10_x64_Linux_201816032300.tar.gz).

**Comment by karianna** [comment]
This may be a test or systemtest issue in which case we'll shift it to that repo

**Comment by karianna** [comment]
Need to re-add SAP vms into the new build process/

**Comment by M-Davies** [comment]
@karianna Is this still an issue? I couldn't see any reference to SAP VM's in systemtest?

**Comment by smlambert** [comment]
We used to build and test it for jdk10 (and since its hotspot based vm, any tests that apply to our hotspot builds would also apply to sapmachine).

**Comment by M-Davies** [comment]
Used to? Do we not still?

**Comment by karianna** [comment]
Added to TSC agenda - not sure if we should continue building SAP

**Comment by smlambert** [comment]
"used to" - I believe only jdk10 was enabled, which is now retired.

**Comment by karianna** [comment]
I've reached out to Goetz.

**Comment by gdams** [comment]
@karianna any update on this?

**Comment by karianna** [comment]
> @karianna any update on this?

Had nothing back
