### ISSUE TITLE
Tools like jstack not working with OpenJDK 8-OpenJ9 

### ISSUE THREAD

**Issue by Param-S** [AdoptOpenJDK/openjdk-build#292]
The commands like jstack, jinfo is available with the build. But when I tried to use it, it reports error. Are we supporting the hotspot specific tools with OpenJ9.

```
docker run --rm -it -v $PWD:/src adoptopenjdk/openjdk8-openj9:jdk8u162-b12_openj9-0.8.0 
root@ef11e4a8deb6:/# which jstack jinfo
/opt/java/openjdk/jdk8u162-b12_openj9-0.8.0/bin/jstack
/opt/java/openjdk/jdk8u162-b12_openj9-0.8.0/bin/jinfo
root@ef11e4a8deb6:/# cd src
root@ef11e4a8deb6:/src# java -showversion LongWait &
[1] 12
root@ef11e4a8deb6:/src# openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ee1e77df1d based on jdk8u162-b12)


root@ef11e4a8deb6:/src# jstack 12
Exception in thread "main" java.lang.ClassCastException: com.ibm.tools.attach.attacher.OpenJ9VirtualMachine incompatible with sun.tools.attach.HotSpotVirtualMachine
	at sun.tools.jstack.JStack.runThreadDump(JStack.java:181)
	at sun.tools.jstack.JStack.main(JStack.java:116)
root@ef11e4a8deb6:/src# jinfo -flag "vm.vendor" 12
Exception in thread "main" java.lang.ClassCastException: com.ibm.tools.attach.attacher.OpenJ9VirtualMachine incompatible with sun.tools.attach.HotSpotVirtualMachine
	at sun.tools.jinfo.JInfo.flag(JInfo.java:148)
	at sun.tools.jinfo.JInfo.main(JInfo.java:81)
```

**Comment by DanHeidinga** [comment]
@Param-S Good question.  OpenJ9 currently provides similar information using its javacore files which can be generated by sending `kill -3` to the JVM.  We're considering supporting the j* suite of tools but haven't had a chance to dig into this yet.

**Comment by DanHeidinga** [comment]
@karianna Can you close this item out?  I've mirrored it to the OpenJ9 project and discussion can continue there.

**Comment by karianna** [comment]
Done, thanks!
