### ISSUE TITLE
Java10 class version in the docker image is lower than that in the nightly build at Adopt

### ISSUE THREAD

**Issue by BeverlyXu** [AdoptOpenJDK/openjdk-build#353]
At Adopt the Java10 nightly build of OpenJ9 has a 

> java.class.version = 54.0

  (see below); whereas the docker image has a version of 53. This has prevented us from running the Spring Boots benchmark, which requires the minimum class version of 54. We expect both to be in sync. 

```
guangjxu@Beverly-Dev2:/mnt/c/srcJava/adoptOpenJDK/jdk-10.0.1+10/bin$ ./java -XshowSettings:properties -version
Property settings:
    awt.toolkit = sun.awt.X11.XToolkit
    com.ibm.cpu.endian = little
    com.ibm.jcl.checkClassPath =
    com.ibm.oti.configuration = scar
    com.ibm.oti.shared.enabled = false
    com.ibm.oti.vm.bootstrap.library.path = /mnt/c/srcJava/adoptOpenJDK/jdk-10.0.1+10/lib/compressedrefs
        /mnt/c/srcJava/adoptOpenJDK/jdk-10.0.1+10/lib
    com.ibm.oti.vm.library.version = 29
    com.ibm.system.agent.path = /mnt/c/srcJava/adoptOpenJDK/jdk-10.0.1+10/lib
    com.ibm.util.extralibs.properties =
    com.ibm.vm.bitmode = 64
    file.encoding = UTF-8
    file.encoding.pkg = sun.io
    file.separator = /
    ibm.signalhandling.rs = false
    ibm.signalhandling.sigchain = true
    ibm.signalhandling.sigint = true
    ibm.system.encoding = UTF-8
    java.awt.fonts =
    java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
    java.awt.printerjob = sun.print.PSPrinterJob
    java.class.path =
    java.class.version = 54.0
```

Docker image from this link has a version of 53. 
https://hub.docker.com/r/adoptopenjdk/openjdk10-openj9/
```
java -XshowSettings:properties -version
spring:     java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
spring:     java.awt.printerjob = sun.print.PSPrinterJob
spring:     java.class.path =
spring:     java.class.version = 53.0
spring:     java.home = /opt/java/openjdk/jdk-10+23
spring:     java.io.tmpdir = /tmp

```
This is the error message that we got from running the docker image of java10 with class version of 53. 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: hello/HelloController has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 53.0
spring:         at java.base/java.lang.ClassLoader.defineClass1(Native Method)
spring:         at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1006)
spring:         at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
spring:         at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
spring:         at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
spring:         at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
spring:         at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
spring:         at java.base/java.security.AccessController.doPrivileged(Native Method)
spring:         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
spring:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:562)
spring:         at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
spring:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:495)
spring:         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
spring:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
spring:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
spring:         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by smlambert** [comment]
FYI, @dinogun

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-docker/issues/27 and #323

**Comment by karianna** [comment]
Closing as a duplicate
