### ISSUE TITLE
Glitch in AO10/J9 pipeline

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#445]
Ref: https://ci.adoptopenjdk.net/view/Pipelines/job/openjdk10_openj9_release_pipeline_scm/3/console
```
groovy.lang.MissingPropertyException: No such property: buildJobNum for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:242)
	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:288)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:292)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:268)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
	at
``

**Comment by sxa555** [comment]
Pipeline has been superceded - assigning to myself to take credit for closing ;-)
