### ISSUE TITLE
There was no fonts in Linux version

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#682]
_From @JamesMung on October 23, 2018 3:54_

JDK Version ; jdk8u181-b13

When I use jasper print PDF in Windows is fine, but for Linux found the error as follow:
```java
Caused by: net.sf.jasperreports.engine.JRRuntimeException: java.io.IOException: Problem reading font data.
        at net.sf.jasperreports.engine.fonts.SimpleFontFace.<init>(SimpleFontFace.java:108)
        at net.sf.jasperreports.engine.fonts.SimpleFontFace.<init>(SimpleFontFace.java:128)
        at net.sf.jasperreports.engine.fonts.SimpleFontFace.getInstance(SimpleFontFace.java:67)
        at net.sf.jasperreports.engine.fonts.SimpleFontFamily.setNormal(SimpleFontFamily.java:99)
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.parseFontFamily(SimpleFontExtensionHelper.java:261)
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.parseFontFamilies(SimpleFontExtensionHelper.java:232)
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.loadFontFamilies(SimpleFontExtensionHelper.java:193)
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.loadFontFamilies(SimpleFontExtensionHelper.java:162)
        at net.sf.jasperreports.engine.fonts.FontExtensionsRegistry.getExtensions(FontExtensionsRegistry.java:56)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:110)
        at net.sf.jasperreports.engine.util.JRStyledTextParser.<clinit>(JRStyledTextParser.java:83)
        ... 73 more
Caused by: java.io.IOException: Problem reading font data.
        at java.awt.Font.createFont0(Font.java:1000)
        at java.awt.Font.createFont(Font.java:877)
        at net.sf.jasperreports.engine.fonts.SimpleFontFace.<init>(SimpleFontFace.java:100)
        ... 83 more
```

Can you help for solve this problem in current version ? And please fix it in future version.

_Copied from original issue: AdoptOpenJDK/openjdk8-releases#16_

**Comment by sxa555** [comment]
HI @JamesMung - I haven't used jasper before - do you have a quick set of instructions to reproduce the error? Also which Linux distribution are you using (it's unclear if this is a JDK issue or something that's supposed to be on the underlying OS).

**Comment by JamesMung** [comment]
Hi @sxa555, I tried to use Oracle JDK of Linux version and it's no problem to print PDF. So I compare between Windows and Linux version. I found Windows version has fonts and config in `jre` directory. But I can't found it from Linux version. So I think this is the problem.

And I tried to copy the font and config from Oracle JDK to Adopt JDK. but it's not work. Can you kindly give the solution to solve it ? And please fix it in further versions.

Distribution : `jdk8u181-b13 Linux x64`

**Comment by thistle1990** [comment]
Hi there, our team hit this problem on various Linux distributions too. (Ubuntu, Centos, Debian etc)
JDK version: jdk8u181-b13

We hit this problem even at a very early phase, when installing our product using installer4j, stack trace as follows: 

`java.lang.NullPointerException
    at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
    at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
    at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
    at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
    at sun.font.SunFontManager$2.run(SunFontManager.java:431)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.font.SunFontManager.<init>(SunFontManager.java:376)
    at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
    at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)
    at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
    at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
    at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
    at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
    at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
    at javax.swing.text.WrappedPlainView.updateMetrics(WrappedPlainView.java:318)
    at javax.swing.text.WrappedPlainView.updateChildren(WrappedPlainView.java:297)
    at javax.swing.text.WrappedPlainView.insertUpdate(WrappedPlainView.java:463)
    at javax.swing.plaf.basic.BasicTextUI$RootView.insertUpdate(BasicTextUI.java:1610)
    at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.insertUpdate(BasicTextUI.java:1869)
    at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
    at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
    at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
    at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
    at javax.swing.text.DefaultEditorKit.read(DefaultEditorKit.java:273)
    at javax.swing.JEditorPane.setText(JEditorPane.java:1416)
    at javax.swing.JEditorPane.<init>(JEditorPane.java:290)
    at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.init(AbstractHeadlessScreenExecutor.java:68)
    at com.install4j.runtime.installer.frontend.headless.ConsoleScreenExecutor.<init>(ConsoleScreenExecutor.java:24)
    at com.install4j.runtime.installer.frontend.headless.InstallerConsoleScreenExecutor.<init>(InstallerConsoleScreenExecutor.java:6)
    at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:88)
    at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:57)
    at com.install4j.runtime.installer.Installer.main(Installer.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
    at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:62)`

Currently we use a workaround to install font dependency by
`apt install fontconfig` 

However, this workaround will change behaviour when our customer switches from Oracle jdk to AdoptOpenJDK, and remains a compatibility issue for us. 

Would the team consider bundle the font config in the JDK and help fix it in further versions?

Cheers,

**Comment by JamesMung** [comment]
Hi @xinyi9, Thanks for your solution. BTW, @sxa555 I tried use these code in my program :
```java
try {
	GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
	File fontsDir = new File(System.getProperty("user.home") + "/fonts"); // fonts dir (*.ttf)
	if(fontsDir.isDirectory()){
		for(File file : fontsDir.listFiles()){
			ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, file));
					
			if(logger.isInfoEnabled()) {
				logger.info("Load font " + file.getName());
			}
		}
	}
} catch (Exception e) {
	e.printStackTrace();
}
```
And it appear `NullPointerException` same as @xinyi9 provided. I wish it would helpful for you.

Distribution : `jdk8u181-b13` `Linux x64`

**Comment by enasser** [comment]
The fonts in jre/lib/fonts directory are taken from closed code in Oracle JDK and missing from openJDK. We need to understand why it is failing only on Linux and not on Windows. Which fonts were trying to create when the failure occurred. @mbvreddy FYI

**Comment by jarnbjo** [comment]
We also ran into this problem today with JDK 11.0.1 and it affects at least the Linux version, but not the Windows version of AdoptOpenJDK. 

The NullPointerException in FontConfiguration.java:1264 is caused by a missing font configuration file, which is not included with the Linux version of AdoptOpenJDK. It is important to notice that the direct cause of the exception is a missing _configuration_ file and not that actual font files are missing.

When the AWT font subsystem is initialized, it will look for a font configuration file in $JAVA_HOME/lib following a naming scheme and priority as described here: https://docs.oracle.com/javase/8/docs/technotes/guides/intl/fontconfig.html

Even if no fonts are provided by the JDK and use of OS provided fonts is not intented or configured, a minimal configuration is required by the AWT font subsystem to initialize without throwing exceptions. Providing a **fontconfiguration.properties** file in **$JAVA_HOME/lib** with the following two lines will at least, to start with, mitigate the problem with the NullPointerException:

```
version=1
sequence.allfonts=default
```

Since _we_ are only using fonts bundled with our application, this is a feasible workaround in our situation. It allows the font subsystem to initialize and we can later without issues load our own fonts from the classpath. I am not sure what happens and YMMV if you try to run an application, which relies on the JDK to provide actual fonts, either as bundled with the JDK or as provided by the operating system.

**Comment by jarnbjo** [comment]
Initially commented on issue 693, but also relevant here:

The NullPointerException in FontConfiguration.java:1264 is caused by a missing font configuration file, which is not included with the Linux version of AdoptOpenJDK. It is important to notice that the direct cause of the exception is a missing _configuration_ file and not that actual font files are missing.

When the AWT font subsystem is initialized, it will look for a font configuration file in $JAVA_HOME/lib following a naming scheme and priority as described here: https://docs.oracle.com/javase/8/docs/technotes/guides/intl/fontconfig.html

Even if no fonts are provided by the JDK and use of OS provided fonts is not intented or configured, a minimal configuration is required by the AWT font subsystem to initialize without throwing exceptions. Providing a **fontconfiguration.properties** file in **$JAVA_HOME/lib** with the following two lines will at least, to start with, mitigate the problem with the NullPointerException:

```
version=1
sequence.allfonts=default
```

Since _we_ are only using fonts bundled with our application, this is a feasible workaround in our situation. It allows the font subsystem to initialize and we can later without issues load our own fonts from the classpath. I am not sure what happens and YMMV if you try to run an application, which relies on the JDK to provide actual fonts, either as bundled with the JDK or as provided by the operating system.

**Comment by jgha99user** [comment]
I also encountered this issue with jdk8u181-b13 on centos 7. I was not able to resolve the issue using this adoptopenjdk. I agree, it would be nice if future releases of adoptopenjdk has font support. Another option, outside java seems to be getting the fonts loaded directly to the linux OS (as the os is the fallback if fonts are not available in java). We didn't test this yet.

**Comment by smcilhinney** [comment]
Just to add to the list of people who have experienced this, I hit this issue when using Apache POI (which uses fonts in the background to size Excel columns etc) on a headless server. In essence jarnbjo is right - the cause of the exception shown in the issue is the lack of the `fontconfig.properties` file, as described here: https://docs.oracle.com/javase/8/docs/technotes/guides/intl/fontconfig.html

In my case this alone wasn't sufficient to remove the issue. For any task that needs an actual font to be present you need two things:
1. The JDK/the system to have some way of finding fonts.
2. At least one font to find - this is where I had additional problems.

No. 1 can be provided by the Java `fontconfig.properties` system, or (on Linux) by the `fontconfig` package - both seem to work. Solving no. 2 means actually having a font file somewhere that your solution to no. 1 can find it. Solution that worked for me (on Centos 6/7) was installing the `fontconfig` and `liberation-sans-fonts` packages (the choice of font is arbitrary, any worked, including manual installs).

Ideally (for my purposes) the JDK distribution would include the Java `fontconfig.properties` *and* at least one default font, just like the Sun distribution does (maybe some more open font to replace Lucidia if licensing is the issue). If that were the case then my code would run with Adopt OJDK out of the box, whereas at the moment there are "hidden" dependencies on bare-bones Linux distributions.

**Comment by echua** [comment]
I was struggling with this until I downloaded Adopt JDK8 with the OpenJ9 JVM.  The Hotspot version does not work and that solved my problems. I wasn't getting many errors at all so finally started from scratch and noticed this.

**Comment by maxpg** [comment]
Does anyone know the progress of this issue? I see in the migration guide that "Relicensed Lucidia Fonts" are "coming soon". It also states Q2 2019.

How is the progress on that? Is it planned to be part of the next Java 8 Update? Is there still potential to slip out of Q2 or is it basically already finished?

**Comment by karianna** [comment]
@maxpg we have the May 2019 milestone label which means it's in the bucket of things that we want to look at next (May is false in terms of timing though). It's an unassigned issue so unless a volunteer picks it up beforehand we won't tackle it until some other priorities get sorted first.

**Comment by moschinski** [comment]
@karianna The issue is a major one if you want to ship your (on-premise) application with AdoptOpenJDK as the application may not work correctly on some Linux distributions. Considering this, I hope that you can give the issue a higher priority and a reliable milestone (waiting half a year because [your page](https://adoptopenjdk.net/migration.html#relicensed-lucida-fonts) states _"expected to complete in 2Q 2019"_ just to see that the issue is still unassigned is somewhat disappointing).

**Comment by karianna** [comment]
> @karianna The issue is a major one if you want to ship your (on-premise) application with AdoptOpenJDK as the application may not work correctly on some Linux distributions. Considering this, I hope that you can give the issue a higher priority and a reliable milestone (waiting half a year because [your page](https://adoptopenjdk.net/migration.html#relicensed-lucida-fonts) states _"expected to complete in 2Q 2019"_ just to see that the issue is still unassigned is somewhat disappointing).

We do our best to prioritize issues that impact the most folks, but this is a community/volunteer project.  If you'd like this particular issue looked at more quickly then we're always looking for more help and/or there are support options listed at adoptopenjdk.net/support.html

**Comment by mduft** [comment]
We're having issues here as well (on AdoptOpenJDK10):

```
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
	... 32 more
Caused by: java.lang.NullPointerException
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1288)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:765)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:440)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:385)
	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
	... 36 more
```
It happens for us on vanilla Fedora 30 (just boot the live CD). Whenever AWT or Swing is used, things go bad... I have no idea what the problem is, libfontconfig.so.1 is present, so I guess it must be something else...

I did test this with the reference build as well (https://jdk.java.net/java-se-ri/10), and this works. So it must be something with AdoptOpenJDK builds... but what?

**Comment by mduft** [comment]
I upgraded to AdoptOpenJDK 11, and this fixed the issue for Fedora 30. I can confirm that fonts work out of the box where they did not with JDK10. We were unable to upgrad to 11 previously due to jersey not supporting it, but now it works :)

```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

**Comment by karianna** [comment]
OK so it sounds like this is still an issue for AdoptOpenJDK 8 but not 11 (potentially)

**Comment by scoobsterscoobster** [comment]
Adding this info in hopes it might help someone or provide some clues, although the exact scenario is a little different than above:

Context:
My application uses a PDF generation tool (Crystal Reports) to generate PDFs.  This runs in a Windows 10 environment.

Short Story:
My issues go away when I create a JAVA_HOME/jre/lib/fonts and add ANY single ttf font that is installed on my system.

Long Story:
On Amazon Corretto 8 or AdoptOpenJDK 8, I get an NPE when Crystal Reports (thrown from its OpenTypeFontManager) is generating a PDF.  Like many people, I tried copying Oracle's font folder to JAVA_HOME/jre/lib/fonts.  In Corretto I get 'java.lang.UnsatisfiedLinkError: <some path>\jre\bin\fontmanager.dll: Can't find dependent libraries', and in AdoptOpenJDK the PDF would generate but with no text, and a few special symbols sprinkled on the page.

I deleted the contents of the 'fonts' folder and copied a single TTF font (webdings.ttf, which is not even used by the PDF) and things worked in both Corretto and AdoptOpenJDK.

I then also added back all of the Oracle fonts (LucidaBrightDemiBold, LucidaBrightDemiItalic, LucidaBrightItalic, LucidaBrightRegular, LucidaSansDemiBold, LucidaTypewriterBold, LucidaTypewriterRegular, LucidaSansRegular) and things failed again.  I then deleted each Oracle font one by one until I discovered that deleting LucidaSansRegular alone was enough to make things work.

Summary:
Copying over the Oracle fonts and deleting LucidaSansRegular OR creating an empty 'fonts' directory and copying one of the OS fonts, made things work in Corretto and AdoptOpenJDK.

**Comment by theredcat** [comment]
Having this issue on Debian 10 while trying to run Jenkins 1.204.1

The @jarnbjo solution worked for me.

I use linux binaries and install them in `/usr/share/java/{java_version}`. Creating /usr/share/java/jdk-11.0.5+10/lib/fontconfig.properties with the following content allowed jenkins to start: 
```
version=1
sequence.allfonts=default
```

**Comment by sxa555** [comment]
@lumpfish is this related to what you were working on recently?

**Comment by lumpfish** [comment]
Some of it, yes.  I was looking for any progress on the The AdoptOpenJDK migration guide (https://adoptopenjdk.net/MigratingtoAdoptOpenJDKfromOracleJava.pdf) statement "The Lucida fonts that are available in Oracle JDK 8 have a proprietary 3rd party license. AdoptOpenJDK intends to provide relicensed Lucida fonts. Work is ongoing to minimize any display issues when these fonts are rendered by Freetype and are expected to complete in 2Q2019."
From this I deduce it is still unresolved.
What needs to be done to "provide relicensed Lucida fonts"?
