### ISSUE TITLE
build-scripts/openjdk11-pipeline git fetch failure

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-build#781]
**Platform:**
win64

**Architecture:**
x86

Please describe the issue that you are having with our binaries and if possible how to recreate it.

Not sure if a build or infra issue, but from https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_windows/54/console output, see that pipelines fail to launch test jobs failing on jdk11 windows builds:

 Started by upstream project "build-scripts/openjdk11-pipeline" build number 196
 originally caused by:
  Started by timer
hudson.plugins.git.GitException: Command "git fetch --tags --progress origin +refs/heads/JDKversion:refs/remotes/origin/JDKversion --prune" returned status code 128:
stdout: 
stderr: fatal: Couldn't find remote ref refs/heads/JDKversion

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1735)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:420)
	at jenkins.plugins.git.GitSCMFileSystem$BuilderImpl.build(GitSCMFileSystem.java:351)
	at jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:198)
	at jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:108)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:292)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE

jdk8 windows pipelines seem to work fine.  Last good jdk11 run was Nov 27th.

**Comment by AdamBrousseau** [comment]
That comes from the Job config
![image](https://user-images.githubusercontent.com/6430052/49252368-dcb02780-f3f1-11e8-9649-2a66e06b03cb.png)

**Comment by smlambert** [comment]
haha, thanks, closing.
