### ISSUE TITLE
java.lang.UnsatisfiedLinkError: sun/print/CUPSPrinter.initIDs()Z exception happens

### ISSUE THREAD

**Issue by takiguc** [AdoptOpenJDK/openjdk-build#824]
Hello.

I used OpenJDK JDK11 for AIX.
Desktop printer feature cannot detect by following exception.
```Caused by: java.lang.UnsatisfiedLinkError: sun/print/CUPSPrinter.initIDs()Z```

Version Information:
```
$ ~/jdk-11.0.1+13/bin/java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 AIX ppc64-64-Bit Compressed References 20181020_75 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9d
OMR      - ea548a6
JCL      - f62696f based on jdk-11.0.1+13)
```
Test instruction:
(Please configure AIX printer)
1. Run following command
```
$ ~/jdk-11.0.1+13/bin/java -jar ~/jdk-11.0.1+13/demo/jfc/SwingSet2/SwingSet2.jar
```
2. Click "JTable demo" button (3rd button from right side)
3. Click "Print" button, then following exception was happened
```
Exception in thread "PrinterListener" java.lang.NoClassDefFoundError: sun.print.CUPSPrinter (initialization failure)         
        at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:141)                             
        at java.desktop/sun.print.PrintServiceLookupProvider.refreshServices(PrintServiceLookupProvider.java:283)            
        at java.desktop/sun.print.PrintServiceLookupProvider$PrinterChangeListener.run(PrintServiceLookupProvider.java:945)  
        at java.base/java.lang.Thread.run(Thread.java:825)                                                                   
Caused by: java.lang.UnsatisfiedLinkError: sun/print/CUPSPrinter.initIDs()Z                                                  
        at java.desktop/sun.print.CUPSPrinter.<clinit>(CUPSPrinter.java:91)                                                  
        at java.desktop/sun.print.PrintServiceLookupProvider.getDefaultPrintService(PrintServiceLookupProvider.java:648)     
        at java.desktop/sun.print.PrintServiceLookupProvider.refreshServices(PrintServiceLookupProvider.java:278)            
        ... 2 more                                                                                                           
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: sun.print.CUPSPrinter (initialization failure)        
        at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:141)                             
        at java.desktop/sun.print.PrintServiceLookupProvider.getDefaultPrintService(PrintServiceLookupProvider.java:648)     
        at java.desktop/javax.print.PrintServiceLookup.lookupDefaultPrintService(PrintServiceLookup.java:206)                
        at java.desktop/sun.print.RasterPrinterJob.getPrintService(RasterPrinterJob.java:462)                                
        at java.desktop/sun.print.RasterPrinterJob.defaultPage(RasterPrinterJob.java:1778)                                   
        at java.desktop/sun.print.RasterPrinterJob.setPrintable(RasterPrinterJob.java:1162)                                  
        at java.desktop/javax.swing.JTable.print(JTable.java:6326)                                                           
        at java.desktop/javax.swing.JTable.print(JTable.java:6185)                                                           
        at java.desktop/javax.swing.JTable.print(JTable.java:6140)                                                           
        at TableDemo.printTable(TableDemo.java:637)                                                                          
        at TableDemo$14.actionPerformed(TableDemo.java:308)                                                                  
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)                             
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)                         
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)                      
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)                               
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)               
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)                                            
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6397)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:673)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:673)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.UnsatisfiedLinkError: sun/print/CUPSPrinter.initIDs()Z
        at java.desktop/sun.print.CUPSPrinter.<clinit>(CUPSPrinter.java:91)
        at java.desktop/sun.print.PrintServiceLookupProvider.getDefaultPrintService(PrintServiceLookupProvider.java:648)
        at java.desktop/sun.print.PrintServiceLookupProvider.refreshServices(PrintServiceLookupProvider.java:278)
        at java.desktop/sun.print.PrintServiceLookupProvider$PrinterChangeListener.run(PrintServiceLookupProvider.java:945)
        at java.base/java.lang.Thread.run(Thread.java:825)
```
The detail information is in https://bugs.openjdk.java.net/browse/JDK-8204541

Following change maybe required for OpenJDK JDK11 with IBM XLC++ 13.1.
```
$ hg di src/java.desktop/unix/native/common/awt/CUPSfuncs.c
diff -r eef755718cb2 src/java.desktop/unix/native/common/awt/CUPSfuncs.c
--- a/src/java.desktop/unix/native/common/awt/CUPSfuncs.c       Wed Dec 05 09:34:01 2018 -0500
+++ b/src/java.desktop/unix/native/common/awt/CUPSfuncs.c       Mon Jan 07 23:28:55 2019 +0900
@@ -27,6 +27,13 @@
 #include <jni_util.h>
 #include <jvm_md.h>
 #include <dlfcn.h>
+
+#ifdef AIX
+#if !defined(__attribute__)
+#define CUPSFUNCS_AIX_NEED_UNDEF_ATTRIBUTE 1
+#endif
+#endif
+
 #include <cups/cups.h>
 #include <cups/ppd.h>
 /*
@@ -39,6 +46,9 @@
 #undef __attribute__
 #endif

+#ifdef CUPSFUNCS_AIX_NEED_UNDEF_ATTRIBUTE
+#undef __attribute__
+#endif

 //#define CUPS_DEBUG

```

**Comment by M-Davies** [comment]
@takiguc @karianna It looks like this was resolved in OpenJ9's [mirror](https://github.com/eclipse/openj9/issues/4184#issuecomment-485446225) of this issue. Can this be closed?

**Comment by karianna** [comment]
> @takiguc @karianna It looks like this was resolved in OpenJ9's [mirror](https://github.com/eclipse/openj9/issues/4184#issuecomment-485446225) of this issue. Can this be closed?

Yes!

**Comment by takiguc** [comment]
Thank for your attention.
For JDK11, following fix was applied:
https://bugs.openjdk.java.net/browse/JDK-8217711
