### ISSUE TITLE
OpenJ9 on macOS cannot run GUI applications

### ISSUE THREAD

**Issue by taku0** [AdoptOpenJDK/openjdk-build#861]
**Platform:**
macOS 10.14.2

**Architecture:**
x86_64

Running a GUI app results in the following error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:191)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:180)
	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
	at java.desktop/java.awt.Window.initGC(Window.java:487)
	at java.desktop/java.awt.Window.init(Window.java:507)
	at java.desktop/java.awt.Window.<init>(Window.java:549)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at JavaSample.startAWT(JavaSample.java:24)
	at JavaSample.main(JavaSample.java:16)
Caused by: java.lang.NullPointerException
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:340)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
	... 7 more
```

Sample code: https://github.com/taku0/JavaSample

Build used: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11U-jdk_x64_mac_openj9_jdk-11.0.1_13_openj9-0.11.0_11.0.1_13.tar.gz

`java --version`:

```
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20181115_16 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dcd
OMR      - ea548a66
JCL      - d4455071ce based on jdk-11.0.1+13)
```

OpenJ9 on Linux works fine.

**Comment by taku0** [comment]
It works on `jdk-11.0.2+9`. Thank you.
