### ISSUE TITLE
Windows JDK8 builds all failing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#996]
See https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u

Example failure from https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-hotspot/227/console:
```
Fetching origin
HEAD is now at 633cbacee4 Merge hotspot at HEAD
Downloading https://services.gradle.org/distributions/gradle-5.2.1-bin.zip

Exception in thread "main" javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1904)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1862)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1845)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1366)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
	at org.gradle.wrapper.Download.download(Download.java:52)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:62)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

**Comment by ali-ince** [comment]
I've updated cacerts files both in jdk-7 and jdk-8 installations and now experiencing another error saying that 

```
Downloading https://services.gradle.org/distributions/gradle-5.2.1-bin.zip

...................................................................................

FAILURE: Build failed with an exception.

* What went wrong:
Gradle 5.2.1 requires Java 8 or later to run. You are currently using Java 7.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

I can get the error, but the default JAVA_HOME is already pointing to jdk-8. I guess the build system overrides default JAVA_HOME with BOOT_JDK which is defined as jdk-7 for jdk-8 builds.

**Comment by karianna** [comment]
Hi @ali-ince - I think #1000 will resolve this issue.

**Comment by sxa555** [comment]
Currently still failing with this:

```
BUILD SUCCESSFUL in 34s
3 actionable tasks: 2 executed, 1 up-to-date
Error: Could not find or load main class ParseVersion
Caused by: java.lang.ClassNotFoundException: ParseVersion
```

**Comment by johnoliver** [comment]
Yeah there is an issue with windows not accepting absolute classpaths #1001 should fix it, but testing now
